// Word Smash — built-in deck library.
// Each card is one word tagged with a board category:
//   { badge: "OBJECT" | "NATURE" | "ACTION" | "PERSON" | "WORLD" | "RANDOM" | "DRAW", title: "..." }
// The board decides the category, then the app pulls a word of that category.
//
// 30 words per category = 210 per deck, matching what AI generation produces.
// That is sized for a full 4-team game: 48 board spaces at one space per correct
// answer means ~40 turns, and at ~5 correct plus ~2 skips a turn that is ~280
// words drawn — so a category only starts repeating late in a long game.
//
// Works fully offline: no AI key, no Worker.
window.BUILTIN_DECKS = (function () {

  // Compact helper: build cards from a {CATEGORY: [words]} map
  function deck(title, audience, icon, blurb, map) {
    const cards = [];
    Object.keys(map).forEach(cat => map[cat].forEach(w => cards.push({ badge: cat, title: w })));
    return { game: "wordsmash", title, audience, icon, blurb, cards };
  }

  return [
  deck("80s & 90s Nostalgia", "adults (clean)", "cassette",
    "Walkmans, mullets and Saturday morning telly. The stuff everyone who grew up then still remembers.", {
      OBJECT: ["Walkman","VHS tape","Rubik's Cube","Game Boy","Tamagotchi","Floppy disk","Boombox","Nokia 3310",
        "Polaroid camera","Cassette","Pager","Discman","Fax machine","Dial-up modem","Zip drive",
        "Overhead projector","Rotary phone","Answering machine","Betamax","Laser disc","Slinky","View-Master",
        "Etch A Sketch","Speak & Spell","Casio watch","Filofax","Trapper Keeper","Lava lamp","Waterbed","Bum bag"],
      NATURE: ["Ozone layer","Halley's Comet","Acid rain","Great white shark","El Niño","Thunderstorm","Rainforest",
        "Coral reef","Bushfire","Dolly the sheep","Killer bees","Mount St Helens","Solar eclipse","Rainbow",
        "Quicksand","Glacier","Tornado","Amazon river","Sand dune","Meteor shower","Volcano","Tidal wave",
        "Blizzard","Locust swarm","Panda","Bald eagle","Redwood tree","Venus flytrap","Northern lights","Hurricane"],
      ACTION: ["Moonwalk","Breakdance","Rollerblade","Headbang","Air guitar","Macarena","Mosh pit","Aerobics",
        "Dial-up","Mixtape making","Rewinding a tape","Blowing a cartridge","Channel surfing","Passing notes",
        "Prank calling","Skateboarding","Roller disco","Bungee jumping","Line dancing","Crimping hair",
        "Renting a video","Taping the radio","Playing pinball","Slam dunking","Hacky sack","Yo-yo tricks",
        "Doing the worm","High-fiving","Grunge moshing","Speed dialling"],
      PERSON: ["Michael Jackson","Madonna","Freddie Mercury","Kurt Cobain","Princess Diana","Mr T","Spice Girls",
        "Britney Spears","Hulk Hogan","Prince","Whitney Houston","Tupac","David Hasselhoff","Macaulay Culkin",
        "Michael J Fox","Arnold Schwarzenegger","Sylvester Stallone","Tom Cruise","Julia Roberts","Jim Carrey",
        "Eddie Murphy","Will Smith","Oprah Winfrey","Michael Jordan","Mike Tyson","George Michael",
        "Cyndi Lauper","Bon Jovi","Axl Rose","Vanilla Ice"],
      WORLD:  ["Berlin Wall","Hollywood","Chernobyl","Times Square","Route 66","Silicon Valley","Video arcade","East Berlin",
        "Moscow","Hong Kong","Seattle","Roller rink","Las Vegas","Woodstock","Graceland","Beverly Hills","Bronx",
        "Tokyo","Drive-in cinema","Video store","Internet cafe","Bermuda Triangle","Phone box","Studio 54","Wall Street","Milk bar",
        "Cape Canaveral","Soviet Union","Twin Towers","Area 51"],
      RANDOM: ["Mullet","Shoulder pads","Scrunchie","Pogs","Slap bracelet","Frosted tips","Fanny pack",
        "Leg warmers","Beanie Baby","Perm","Parachute pants","Neon windbreaker","Doc Martens","Chokers","Overalls",
        "Bucket hat","Shell suit","Stonewash jeans","Jelly shoes","Snap bracelet","Furby","Troll doll","Pet rock",
        "Magic Eye","Chain wallet","Butterfly clips","Platform sneakers","Puka shells","Body glitter","Baggy jeans"],
      DRAW:   ["A DeLorean","Pac-Man","A ghetto blaster","Neon sunglasses","A skateboard","A cassette tape",
        "Space Invaders","A Ninja Turtle","A Tamagotchi","A boombox on a shoulder","A rubik's cube","A Game Boy",
        "A floppy disk","A shell suit","A mullet","A brick phone","A jukebox","A roller skate","A lava lamp",
        "A yo-yo","A bum bag","A Furby","A pager","A slap bracelet","An arcade machine","A VHS tape",
        "A skateboard ramp","A pair of Doc Martens","A cassette player","A disco ball"],
  }),

  deck("Aussie Everything", "family friendly", "aus",
    "Eskies, magpies and the backyard barbie. Home ground advantage for anyone who grew up here.", {
      OBJECT: ["Esky","Hills Hoist","Meat pie","Boomerang","Thongs","Zinc stick","Ute","Goon bag","Cricket bat",
        "Surfboard","Akubra","Ugg boots","Stubby holder","Bottle opener","Wheelie bin","Clothesline peg",
        "Beach towel","Zooper Dooper","Milk crate","Tinnie","Fishing rod","Barbecue tongs","Camp chair","Swag",
        "Fly screen","Sunscreen","Beach cricket set","Cattle dog lead","Water tank","Letterbox"],
      NATURE: ["Koala","Kangaroo","Platypus","Kookaburra","Redback spider","Wombat","Echidna","Magpie",
        "Great Barrier Reef","Blue-ringed octopus","Emu","Dingo","Cockatoo","Possum","Goanna","Quokka",
        "Tasmanian devil","Bottlebrush","Wattle","Gum tree","Cane toad","Crocodile","Stingray","Frilled lizard",
        "Bilby","Numbat","Lorikeet","Jellyfish","Bull ant","Sugar glider"],
      ACTION: ["Barbie","Surfing","Backyard cricket","Chuck a sickie","Bushwalk","Sausage sizzle","Swooping",
        "Shoey","Catching a wave","Snag flipping","Watching the footy","Doing a lap","Having a squiz",
        "Slip slop slap","Camping","Fishing off the jetty","Footy tipping","Chucking a uey","Rocking up",
        "Knocking off","Ducking out","Beach cricket","Bushfire watching","Riding a scooter","Popping to the shops",
        "Firing up the barbie","Cracking a tinnie","Hanging washing","Feeding the chooks","Mowing the lawn"],
      PERSON: ["Steve Irwin","Ned Kelly","Cathy Freeman","Don Bradman","Kylie Minogue","John Howard","Paul Hogan",
        "The Wiggles","Hugh Jackman","Barry Humphries","Shane Warne","Ash Barty","Ricky Ponting","Bindi Irwin",
        "Nick Cave","Missy Higgins","Adam Goodes","Nicole Kidman","Chris Hemsworth","Margot Robbie",
        "Russell Crowe","Rebel Wilson","Bob Hawke","Julia Gillard","John Farnham","Jimmy Barnes",
        "Olivia Newton-John","Rod Laver","Greg Norman","Banjo Paterson"],
      WORLD:  ["Uluru","Bondi Beach","Sydney Opera House","Great Ocean Road","Gold Coast","Outback",
        "Blue Mountains","Melbourne laneway","Kakadu","Twelve Apostles","Harbour Bridge","Byron Bay","Cairns",
        "Perth","Adelaide","Darwin","Tasmania","Fraser Island","Kangaroo Island","Snowy Mountains","Alice Springs",
        "Margaret River","Whitsundays","Barossa Valley","Port Douglas","MCG","Nullarbor","Daintree","Broome",
        "Coober Pedy"],
      RANDOM: ["Vegemite","Fairy bread","Lamington","Tim Tam","Servo pie","Milk bar","Sunnies","Arvo","Servo",
        "Bottle-o","Chook","Ute muster","Bogan","Cossie","Doona","Op shop","Ripper","Fair dinkum","She'll be right",
        "Yeah nah","Cane toad race","Meat raffle","Snag sandwich","Sausage in bread","Two-up","Melbourne Cup",
        "Boxing Day Test","Schoolies","Straya Day","Footy finals"],
      DRAW:   ["A kangaroo","A meat pie","A Hills Hoist","A surfboard","A boomerang","An esky","A koala in a tree",
        "A pair of thongs","A ute","A magpie swooping","The Opera House","Ayers Rock at sunset","A lamington",
        "A Tim Tam","A cricket bat","A wombat","A platypus","A bin chicken","A barbie","A swag",
        "The Harbour Bridge","A kookaburra","A Vegemite jar","A stubby holder","A cane toad","A shark warning sign",
        "A beach umbrella","A campfire","A cattle dog","A road train"],
  }),

  deck("Kids Zone", "family friendly", "balloon",
    "Simple, friendly words the whole table can shout out. Nothing anyone needs explaining.", {
      OBJECT: ["Teddy bear","Skateboard","Balloon","Backpack","Crayon","Bicycle","Kite","Lunchbox","Torch",
        "Skipping rope","Bucket","Spade","Football","Puzzle","Marble","Yo-yo","Whistle","Drum","Scooter",
        "Sandcastle","Toy car","Building block","Water pistol","Bubble wand","Paint brush","Sticker","Board game",
        "Piggy bank","Umbrella","Kaleidoscope"],
      NATURE: ["Rainbow","Butterfly","Puppy","Kitten","Snowflake","Sunflower","Ladybird","Frog","Rabbit","Duckling",
        "Tadpole","Caterpillar","Acorn","Seashell","Starfish","Penguin","Dolphin","Elephant","Giraffe","Monkey",
        "Bumblebee","Snail","Owl","Hedgehog","Squirrel","Turtle","Panda","Daisy","Pine cone","Puddle"],
      ACTION: ["Jumping","Skipping","Splashing","Giggling","Tiptoeing","Cartwheeling","Blowing bubbles",
        "Hide and seek","Colouring in","Building a fort","Piggyback ride","Somersault","Clapping","Whistling",
        "Tickling","Waving","Swinging","Sliding","Hopping","Spinning","Sneezing","Yawning","Marching","Dancing",
        "Tiptoe running","Rolling downhill","Blowing a candle","Popping a balloon","Skipping stones",
        "Climbing a tree"],
      PERSON: ["Taylor Swift","Cristiano Ronaldo","Lionel Messi","Steve Irwin","Bindi Irwin","David Attenborough",
        "Ed Sheeran","Beyoncé","Dwayne Johnson","Serena Williams","Usain Bolt","Michael Jordan","Katy Perry",
        "Justin Bieber","Ariana Grande","Harry Styles","Adele","Bruno Mars","Billie Eilish","Dua Lipa","MrBeast",
        "Emma Watson","Daniel Radcliffe","Tom Holland","Zendaya","Simone Biles","Neil Armstrong","Albert Einstein",
        "Roald Dahl","Walt Disney"],
      WORLD:  ["Playground","Zoo","Beach","Farm","Library","Treehouse","Circus","Museum","Swimming pool","Campsite",
        "Aquarium","Toy shop","Bakery","Park","Ice rink","Castle","Lighthouse","Bus stop","Fairground",
        "Petting zoo","Forest","Cave","Island","Desert","Mountain","Rocket ship","Igloo","Windmill","Bridge",
        "Waterfall"],
      RANDOM: ["Bubble","Sprinkles","Glitter","Tickle","Wiggle","Hiccup","Freckle","Pyjamas","Bedtime story",
        "Tooth fairy","Birthday cake","Party hat","Balloon animal","Face paint","Piñata","Lemonade stand",
        "Sleepover","Hopscotch","Musical chairs","Show and tell","Silly face","Bear hug","Secret handshake",
        "Snow day","Puddle jumping","Nap time","Playdate","Dress-up box","Sandpit","Wobbly tooth"],
      DRAW:   ["A smiling sun","A rocket","A cat","A house","A rainbow","A dinosaur","A robot","An ice cream",
        "A flower","A boat","A butterfly","A snowman","A tree","A fish","A birthday cake","A hot air balloon",
        "A castle","A dog","A star","A car","A ladybird","A kite","A frog","A crown","A pirate ship","An umbrella",
        "A snail","A duck","A cupcake","A teddy bear"],
  }),

  deck("Movies & TV", "adults (clean)", "clapper",
    "Blockbusters, cult classics and the shows people still quote at each other.", {
      OBJECT: ["Popcorn bucket","Film reel","Clapperboard","Remote control","3D glasses","Cinema ticket",
        "Red carpet","Oscar statue","Boom mic","Director's chair","Green screen","Movie poster","DVD box set",
        "Projector","Ticket stub","Velvet rope","Usher torch","Slushie cup","Screen curtain","Camera dolly",
        "Storyboard","Prop sword","Fake blood","Wind machine","Stunt harness","Teleprompter","Subtitle bar",
        "Rating sticker","Cinema seat","Concession stand"],
      NATURE: ["Jurassic jungle","Shark fin","King Kong's island","Twister","Desert planet","Volcano lair",
        "Haunted forest","Snowy tundra","Deep space","Ocean trench","Swamp","Savannah","Jungle vine","Cliff edge",
        "Torrential rain","Blood red sunset","Meteor strike","Iceberg","Sand storm","Canyon","Alien landscape",
        "Coral lagoon","Piranha river","Bamboo forest","Moon surface","Thunder and lightning","Wolf howl",
        "Giant eagle","Creeping fog","Cave system"],
      ACTION: ["Binge watching","Skipping the intro","Rewinding a scene","Pausing to snack","Quoting a film",
        "Booing a villain","Cheering the hero","Crying at the end","Queuing for tickets","Auditioning",
        "Method acting","Improvising","Lip syncing","Screen testing","Stunt doubling","Directing","Editing",
        "Voice acting","Spoiling the ending","Live tweeting","Arguing about the ending","Walking the red carpet",
        "Taking a bow","Applauding","Sneaking snacks in","Reading subtitles","Filming a montage",
        "Rolling the credits","Rating a film","Sitting through the credits"],
      PERSON: ["Tom Hanks","Meryl Streep","Leonardo DiCaprio","Denzel Washington","Julia Roberts",
        "Steven Spielberg","Quentin Tarantino","Morgan Freeman","Robert De Niro","Al Pacino","Samuel L Jackson",
        "Scarlett Johansson","Brad Pitt","Angelina Jolie","Will Smith","Jennifer Aniston","Robin Williams",
        "Jim Carrey","Eddie Murphy","Arnold Schwarzenegger","Keanu Reeves","Cate Blanchett","Oprah Winfrey",
        "Ricky Gervais","Steve Carell","Bryan Cranston","Tom Cruise","Harrison Ford","Anthony Hopkins",
        "Charlie Chaplin"],
      WORLD:  ["Hogwarts","Middle-earth","Gotham City","Jurassic Park","The Shire","Wakanda","Hill Valley",
        "Springfield","Westeros","Pandora","Narnia","Neverland","Oz","Death Star","Bikini Bottom","Mordor",
        "The Matrix","Tatooine","Hollywood Boulevard","Sunnydale","Bedrock","Duckburg","Metropolis","Atlantis",
        "Isla Nublar","Arrakis","The Upside Down","Stars Hollow","Amity Island","Zootopia"],
      RANDOM: ["Sequel","Reboot","Cameo","Blooper","Cliff-hanger","Spin-off","Binge","Trailer","Post-credits scene",
        "Box office","Franchise","Fan theory","Season finale","Pilot episode","Streaming","Subtitles","Dubbing",
        "Soundtrack","Screenplay","Casting","Prequel","Anti-hero","Sidekick","Nemesis","Plot armour","Catchphrase",
        "Laugh track","Blockbuster","Award season","Cult classic"],
      DRAW:   ["A film clapperboard","Popcorn","A cinema screen","A movie camera","A red carpet","An Oscar",
        "A 3D pair of glasses","A director's chair","A ticket stub","A film reel","A lightsaber","A wizard hat",
        "A shark fin","A DeLorean","A dinosaur","A superhero cape","A crown","A spaceship","A cowboy hat","A ring",
        "A haunted house","A pirate flag","A robot","A detective magnifier","A microphone","A boom mic",
        "A projector","A drive-in screen","A movie poster","A theatre curtain"],
  }),

  deck("Sports Legends", "teens", "trophy",
    "Players, moments and gear from across the codes. You don't have to be a fanatic to get these.", {
      OBJECT: ["Football","Cricket bat","Tennis racquet","Boxing glove","Surfboard","Golf club","Hockey stick",
        "Basketball","Whistle","Stopwatch","Goal post","Scoreboard","Trophy","Medal","Shin pad","Mouthguard",
        "Swim goggles","Running spikes","Baseball mitt","Helmet","Skipping rope","Weight bench","Yellow card",
        "Starting block","Ski poles","Netball bib","Water bottle","Bike helmet","Dartboard","Bowling ball"],
      NATURE: ["Mountain","Ocean","Rapids","Snowfield","Sand dune","Gale","Mud","Blazing sun","Reef",
        "Alpine forest","Desert","Frozen lake","Forest","Heatwave","Fog","Ocean current","Snowstorm","Hailstorm",
        "Sea spray","Cliff","Waterfall","Glacier","Canyon","Thunderstorm","Lightning","Blizzard","Tide",
        "Headland","Rockface","Whitewater"],
      ACTION: ["Slam dunk","Home run","Hat-trick","Penalty kick","Bowled out","Try scored","Knockout",
        "Photo finish","Sprint","Tackle","Marathon","Dive","Backflip","Volley","Free throw","Lay-up","Sledging",
        "Streaking","Warming up","Cooling down","Substitution","Time out","Half time","Overtime","Extra time",
        "Lap of honour","Podium finish","Post-match interview","Coin toss","Full time whistle"],
      PERSON: ["Michael Jordan","Serena Williams","Usain Bolt","Muhammad Ali","Pelé","Cathy Freeman","Shane Warne",
        "Tiger Woods","Roger Federer","Lionel Messi","Cristiano Ronaldo","Simone Biles","Ash Barty","Don Bradman",
        "Ian Thorpe","Layne Beachley","Sally Pearson","Adam Goodes","Rafael Nadal","Lewis Hamilton",
        "Diego Maradona","Sam Kerr","Ellyse Perry","Michael Phelps","LeBron James","Ayrton Senna",
        "Dylan Alcott","Emma McKeon","Babe Ruth","Martina Navratilova"],
      WORLD:  ["Olympic stadium","Camp Nou","Wimbledon","MCG","Alpe d'Huez","Yankee Stadium","Lord's",
        "Suncorp Stadium","Flemington","Eden Park","Wembley","Old Trafford","Maracanã",
        "Madison Square Garden","Augusta","Monaco circuit","Bondi","Everest base camp","Kokoda Track",
        "Bells Beach","Rio","Tokyo","Paris","Barcelona","Sydney","Athens","Beijing","Los Angeles","Brisbane",
        "Manchester"],
      RANDOM: ["Offside","Red card","Sudden death","Underdog","Rivalry","Team jersey","Half-time orange",
        "Fantasy league","Transfer window","Draft pick","Bench warmer","Season ticket","Sportsmanship","Trash talk",
        "Comeback","Winning streak","Losing streak","Hall of fame","Record breaker","Dark horse","Home advantage",
        "Away game","Derby","Testimonial","Warm-up lap","Drug test","Injury time","Man of the match","Wooden spoon",
        "Grand slam"],
      DRAW:   ["A football","A trophy","A medal","A whistle","A goal post","A cricket bat","A tennis racquet",
        "A boxing glove","A surfboard","A basketball hoop","A running shoe","A stopwatch","A scoreboard","A podium",
        "A referee","A helmet","A bicycle","A swimming pool","A dartboard","A golf flag","A red card",
        "A skateboard","A ski slope","A finish line","A weight","A jersey","A hockey stick","A baseball mitt",
        "A pair of goggles","A racing car"],
  }),

  deck("Around the House", "family friendly", "house",
    "Everyday things hiding in plain sight, which turns out to be far harder to describe than it sounds.", {
      OBJECT: ["Kettle","Toaster","Doorbell","Coat hanger","Ironing board","Vacuum cleaner","Mop","Laundry basket",
        "Bin lid","Tea towel","Doormat","Light switch","Curtain rail","Fridge magnet","Bread bin","Chopping board",
        "Colander","Whisk","Peeler","Corkscrew","Torch","Extension cord","Smoke alarm","Sewing kit","Toolbox",
        "Spirit level","Watering can","Step ladder","Clothes peg","Dustpan"],
      NATURE: ["Houseplant","Lawn","Weeds","Compost heap","Veggie patch","Spider web","Mould","Dust",
        "Fallen leaves","Moth","Bird nest","Hedge","Rose bush","Ant","Spider","Snail","Ladybird","Earthworm",
        "Possum","Mouse","Cockroach","Fern","Ivy","Lavender","Tomato plant","Dandelion","Butterfly","Beehive",
        "Frost","Puddle"],
      ACTION: ["Vacuuming","Washing up","Hanging washing","Mowing the lawn","Taking the bins out","Making the bed",
        "Folding laundry","Dusting","Changing a bulb","Locking up","Defrosting the freezer","Unblocking the sink",
        "Watering plants","Sweeping","Ironing","Cooking dinner","Setting the table","Doing the dishes",
        "Painting a wall","Hammering a nail","Hanging a picture","Assembling flat-pack","Reading the meter",
        "Sorting recycling","Cleaning windows","Wiping benches","Feeding the pet","Scrubbing the shower",
        "Changing sheets","Putting up shelves"],
      PERSON: ["Martha Stewart","Marie Kondo","Scott Cam","Jamie Durie","Shaynna Blaze","Neale Whitaker",
        "Darren Palmer","Barry Du Bois","Costa Georgiadis","Don Burke","Peter Cundall","Andrew Winter",
        "Johanna Griggs","Graham Ross","Dr Harry Cooper","Mrs Hinch","Kirstie Allsopp","Phil Spencer",
        "Kevin McCloud","Laurence Llewelyn-Bowen","Ty Pennington","Chip Gaines","Joanna Gaines","Tan France",
        "Jonathan Van Ness","Tim Allen","Kim Woodburn","Charlie Albone","Adam Dovile","Sarah Beeny"],
      WORLD:  ["Kitchen","Bathroom","Garage","Attic","Basement","Backyard","Hallway","Laundry","Pantry",
        "Spare room","Front porch","Shed","Balcony","Driveway","Letterbox","Garden path","Rooftop","Staircase",
        "Cupboard under the stairs","Linen closet","Nursery","Study","Sunroom","Deck","Carport","Courtyard","Loft",
        "Cellar","Utility room","Front gate"],
      RANDOM: ["Missing sock","Junk drawer","Squeaky door","Blown fuse","Leaky tap","Loose floorboard","Spare key",
        "Odd spoon","Dead batteries","Wrong-size screw","Tangled cables","Half-used paint tin","Expired sauce",
        "Random remote","Instruction manual","Broken zip","Old phone charger","Mystery stain","Fridge leftovers",
        "Dodgy shelf","Chore roster","Shopping list","Power bill","Spare button","Rusty hinge","Sticky drawer",
        "Draughty window","Wonky table leg","Warranty card","Blunt scissors"],
      DRAW:   ["A kettle","A toaster","A vacuum cleaner","A mop and bucket","A washing machine","A front door",
        "A letterbox","A lawnmower","A ladder","A light bulb","A house plant","A garden hose","A bin",
        "A clothesline","A doormat","A tap dripping","A hammer","A screwdriver","A paint roller","A wheelbarrow",
        "A sofa","A bed","A dining table","A fridge","A shower","A staircase","A window","A chimney",
        "A garden gnome","A shed"],
  }),

  deck("Music Icons", "teens", "note",
    "Artists, instruments and the songs that get sung badly at every party.", {
      OBJECT: ["Electric guitar","Drum kit","Microphone","Vinyl record","Headphones","Keyboard","Amplifier",
        "Saxophone","Tambourine","Turntable","Guitar pick","Drum stick","Violin","Harmonica","Trumpet","Ukulele",
        "Speaker stack","Mixing desk","Setlist","Tour bus","Backstage pass","Stage light","Smoke machine","Capo",
        "Banjo","Cello","Bass guitar","Piano stool","Music stand","Metronome"],
      NATURE: ["Nightingale","Songbird","Dawn chorus","Whale song","Wolf","Cricket","Birdsong","Thunder",
        "Ocean waves","Babbling brook","Waterfall","Canyon","Cave","Howling wind","Rain","Beehive","Frog",
        "Cicada","Kookaburra","Magpie","Humpback whale","Lyrebird","Mockingbird","Canary","Cockatoo",
        "Woodpecker","Owl","Seagull","Echo","Storm"],
      ACTION: ["Headbanging","Crowd surfing","Air guitar","Singing along","Busking","Jamming","Beatboxing","DJing",
        "Moshing","Taking a bow","Sound check","Lip syncing","Freestyling","Harmonising","Whistling a tune",
        "Tapping a beat","Clapping along","Waving a lighter","Stage diving","Dropping the bass","Recording a demo",
        "Going on tour","Signing autographs","Warming up vocals","Tuning a guitar","Writing lyrics","Sampling",
        "Remixing","Conducting","Drum solo"],
      PERSON: ["Elvis Presley","The Beatles","Beyoncé","Freddie Mercury","Taylor Swift","Bob Marley","Dolly Parton",
        "Michael Jackson","Adele","Ed Sheeran","Nirvana","Queen","AC/DC","INXS","Prince","Whitney Houston",
        "David Bowie","Rihanna","Bruno Mars","Billie Eilish","Bruce Springsteen","Aretha Franklin",
        "Amy Winehouse","Johnny Cash","Bob Dylan","Jimi Hendrix","Tina Turner","Elton John","Stevie Wonder","Usher"],
      WORLD:  ["Abbey Road","Nashville","Glastonbury","Coachella","Sydney Opera House","Woodstock","Motown",
        "Broadway","Ibiza","Detroit","Liverpool","New Orleans","Memphis","Hollywood Bowl","Vienna",
        "Splendour in the Grass","Tamworth","Royal Albert Hall","Carnegie Hall","Red Rocks","Recording studio",
        "Concert hall","Music festival","Karaoke bar","Record shop","Rehearsal room","Radio station","Nightclub",
        "Busker corner","Grand Ole Opry"],
      RANDOM: ["Earworm","One-hit wonder","Album cover","Encore","Chart topper","Guilty pleasure","Karaoke",
        "Playlist","Mixtape","Fan club","Boy band","Girl group","Cover version","Duet","Riff","Chorus","Bridge",
        "Falsetto","Power ballad","Air drums","Vinyl revival","Streaming numbers","Gold record","Groupie",
        "Band merch","Festival wristband","Dad rock","Autotune","Lyric video","Support act"],
      DRAW:   ["An electric guitar","A drum kit","A microphone","A vinyl record","A pair of headphones","A piano",
        "A saxophone","A trumpet","A speaker","A DJ deck","A music note","A tambourine","A guitar pick","A violin",
        "A harmonica","A ukulele","A boombox","A stage","A tour bus","A concert crowd","A cassette",
        "A conductor's baton","A treble clef","A jukebox","A megaphone","A festival tent","A wristband",
        "A vinyl sleeve","A metronome","A karaoke machine"],
  }),

  deck("Food & Drink", "family friendly", "cup",
    "Meals, snacks and drinks. Easy to picture, surprisingly tricky to describe without saying the word.", {
      OBJECT: ["Frying pan","Wooden spoon","Rolling pin","Cheese grater","Teapot","Cutting board","Whisk",
        "Baking tray","Measuring cup","Can opener","Cocktail shaker","Salad bowl","Pepper grinder","Ice tray",
        "Lunch box","Thermos","Straw","Corkscrew","Toaster","Blender","Barbecue plate","Pizza cutter","Egg cup",
        "Mixing bowl","Ladle","Slow cooker","Coffee plunger","Sushi mat","Skewer","Apron"],
      NATURE: ["Tomato vine","Apple tree","Beehive","Wheat field","Coffee bean","Cocoa pod","Olive grove",
        "Hop field","Herb garden","Wild truffle","Lemon tree","Chilli plant","Corn field","Rice paddy",
        "Maple tree","Salt flats","Fresh water spring","Cinnamon bark","Berry bush","Pumpkin vine","Avocado tree",
        "Banana palm","Mango tree","Potato field","Strawberry patch","Grapevine","Peanut plant","Sunflower seed",
        "Fig tree","Wild mint"],
      ACTION: ["Barbecuing","Baking","Boiling","Whisking","Kneading","Marinating","Toasting","Grilling","Simmering",
        "Chopping","Peeling","Stirring","Flipping a pancake","Icing a cake","Slicing bread","Frying an egg",
        "Making a sandwich","Setting the table","Pouring a drink","Blowing on soup","Doing the dishes",
        "Ordering takeaway","Booking a table","Sharing dessert","Snacking","Meal prepping","Taste testing",
        "Seasoning","Plating up","Washing veggies"],
      PERSON: ["Gordon Ramsay","Jamie Oliver","Nigella Lawson","Julia Child","Matt Moran","Neil Perry",
        "Colin Fassnidge","Marion Grasby","Curtis Stone","Maggie Beer","Matt Preston","Anthony Bourdain",
        "Heston Blumenthal","Mary Berry","Paul Hollywood","Wolfgang Puck","Ina Garten","Guy Fieri",
        "Marco Pierre White","Rick Stein","Adriano Zumbo","Poh Ling Yeow","Manu Feildel","Ainsley Harriott",
        "Julie Goodwin","Donna Hay","Kylie Kwong","Adam Liaw","Gary Mehigan","Melissa Leong"],
      WORLD:  ["Bakery","Farmers market","Food truck","Fish and chip shop","Cafe","Vineyard","Pizzeria",
        "Ice cream parlour","Night market","Buffet","Supermarket","Butcher shop","Bistro","Beer garden",
        "Rooftop bar","Diner","Sushi train","Deli","Orchard","Brewery","Country pub","Street food stall",
        "Bakery window","Fruit stand","Cellar door","Test kitchen","Canteen","Picnic spot","Barbecue area",
        "Food hall"],
      RANDOM: ["Leftovers","Secret recipe","Food coma","Midnight snack","Doggy bag","Brunch","Side dish",
        "Comfort food","Guilty pleasure","Spice level","Recipe fail","Burnt toast","Soggy chips","Melted ice cream",
        "Fizzy drink","Second helping","Sharing platter","Dessert menu","Happy hour","Takeaway night",
        "Packed lunch","Picnic blanket","Hot sauce","Pickle jar","Cheese board","Roast dinner","Sunday lunch",
        "Street food","Meal deal","Bottomless cup"],
      DRAW:   ["A pizza slice","An ice cream cone","A burger","A cup of coffee","A birthday cake","A banana",
        "A pineapple","A hot dog","A fried egg","A cupcake","A teapot","A wine glass","A watermelon slice",
        "A bunch of grapes","A loaf of bread","A doughnut","A bowl of noodles","A taco","A milkshake",
        "A chef's hat","A frying pan","A barbecue","A picnic basket","A lollipop","A pretzel","A sushi roll",
        "A carrot","A chilli","A jar of honey","A toaster with toast"],
  }),

  deck("Adults After Dark 🔞", "adults (spicy)", "moon",
    "Rude, cheeky and firmly after bedtime. Keep this one away from the kids' table.", {
      OBJECT: ["Handcuffs","Lace lingerie","Whipped cream","Red wine","Tequila shot","Feather boa","Silk sheets",
        "Massage oil","Pole dancing pole","Blindfold","Fishnet stockings","Corset","High heels","Bar tab","Fake ID",
        "Beer bong","Playing cards","Dice cup","Karaoke mic","Neon sign","Bottle of bubbly","Cigar","Poker chips",
        "Lipstick","Little black dress","Bow tie","Champagne flute","Hip flask","Chocolate body paint","Mirror ball"],
      NATURE: ["Melons","Moonlit beach","Hot spring","Secluded waterfall","Beaver","Full moon",
        "Peach","Banana","Love birds","Rabbit","Stallion","Lioness","Snake","Peacock","Bull",
        "Coconuts","Cherry","Cucumber","Night owl","Mating season","Morning dew",
        "Tropical storm","Steamy jungle","Volcano heat","Deserted cove","Pussy willow","Starry night",
        "Birds and the bees","Eggplant","Heatwave"],
      ACTION: ["Flirting","Skinny dipping","Pub crawl","Strip poker","Speed dating","Sliding into DMs","Ghosting",
        "Swiping right","Hangover","Walk of shame","Truth or dare","Spin the bottle","Body shot",
        "Shotgunning a beer","Karaoke duet","Last orders","Cheeky snog","Chatting someone up","Blind date",
        "Beer pong","Dad dancing","Kicking on","Big night out","Sneaking out","Making eyes","Late-night kebab",
        "Hair of the dog","Boozy brunch","Bar hopping","Nightcap"],
      PERSON: ["Marilyn Monroe","Hugh Hefner","Bettie Page","Brigitte Bardot","Sophia Loren","Raquel Welch",
        "Farrah Fawcett","Elizabeth Taylor","Mae West","Casanova","Cleopatra","Errol Flynn","Madonna","Cher",
        "Dita Von Teese","Lady Gaga","Mick Jagger","Barry White","Tom Jones","Prince","Rod Stewart",
        "Warren Beatty","George Clooney","Fabio","Pamela Anderson","Paris Hilton","Kim Kardashian",
        "Jennifer Lopez","Shakira","Russell Brand"],
      WORLD:  ["Las Vegas","Amsterdam","Ibiza","Nightclub","Strip club","Casino","Honeymoon suite","Kings Cross",
        "Rio carnival","Bourbon Street","Bali","Magaluf","Monte Carlo","Speakeasy","Hotel bar","Hotel jacuzzi",
        "Cruise ship","Bachelor pad","Love hotel","Red light district","Bangkok","New Orleans","Berlin club",
        "Vegas chapel","Beach club","Penthouse","Dive bar","Cabaret","Burlesque show","Pool party"],
      RANDOM: ["Hickey","Dad bod","Beer goggles","Netflix and chill","Booty call","Wingman rules","Bad tattoo",
        "Regrettable text","Dirty martini","Hangxiety","Ex's new partner","Love bite","Bar tab shock","Morning after",
        "Drunk dial","Slurred speech","Kebab shop queue","Sneaky pash","Cheeky Nando's","Last drinks",
        "Awkward silence","Flirty emoji","Red flag","Green flag","Situationship","Rebound","Dating app bio",
        "Group chat gossip","Wedding speech","Bad chat-up line"],
      DRAW:   ["A cocktail","A pair of handcuffs","A pair of high heels","A love heart","A wine glass",
        "A disco ball","A pair of lips","A neon sign","A bottle of champagne","A pair of dice","A poker hand",
        "A martini","A bow tie","A lipstick","A rose","A candle","A hot tub","A bed","A cocktail umbrella",
        "A shot glass","A leather jacket","A tattoo","A key to a hotel room","A do not disturb sign","A moon",
        "A cigar","A limousine","A microphone stand","A love letter","A pair of sunglasses at night"],
  }),

  deck("Classic Mixed Bag", "adults (clean)", "dice",
    "A bit of everything, so no single person at the table has the advantage.", {
      OBJECT: ["Umbrella","Wallet","Suitcase","Compass","Telescope","Hourglass","Padlock","Wheelbarrow","Anchor",
        "Ladder","Typewriter","Globe","Binoculars","Magnifying glass","Chessboard","Piano","Bicycle","Lantern",
        "Mirror","Basket","Rope","Bucket","Shovel","Broom","Candle","Camera","Newspaper","Backpack","Clock","Kite"],
      NATURE: ["Volcano","Waterfall","Glacier","Desert","Rainforest","Coral reef","Thunderstorm","Avalanche","Cave",
        "Canyon","Tornado","Earthquake","Iceberg","Sand dune","Geyser","Swamp","Meadow","Fjord","Tundra","Savannah",
        "Lightning","Eclipse","Comet","Rainbow","Tide","Monsoon","Whirlpool","Sinkhole","Delta","Reef"],
      ACTION: ["Juggling","Whistling","Tiptoeing","Yawning","Sneezing","Snoring","Shivering","Wrestling",
        "Skydiving","Hitchhiking","Camping","Fishing","Knitting","Gardening","Painting","Sculpting","Meditating",
        "Stretching","Sprinting","Swimming","Climbing","Digging","Rowing","Sailing","Cycling","Bargaining",
        "Queuing","Celebrating","Apologising","Daydreaming"],
      PERSON: ["Albert Einstein","Cleopatra","Leonardo da Vinci","Marie Curie","Nelson Mandela",
        "William Shakespeare","Amelia Earhart","Neil Armstrong","Mozart","Frida Kahlo","Isaac Newton",
        "Julius Caesar","Joan of Arc","Charles Darwin","Vincent van Gogh","Mahatma Gandhi","Queen Elizabeth",
        "Napoleon","Rosa Parks","Alexander Fleming","Abraham Lincoln","Martin Luther King Jr",
        "Winston Churchill","Beethoven","Michelangelo","Anne Frank","Florence Nightingale","Nikola Tesla",
        "Galileo","Jane Austen"],
      WORLD:  ["Eiffel Tower","Great Wall of China","Pyramids","Colosseum","Taj Mahal","Machu Picchu","Stonehenge",
        "Grand Canyon","Niagara Falls","Mount Everest","Venice","Tokyo","Cairo","Rome","Paris","Amazon rainforest",
        "Sahara","Antarctica","Iceland","Serengeti","New York","London","Istanbul","Athens","Petra","Angkor Wat",
        "Easter Island","Galápagos","Santorini","Kyoto"],
      RANDOM: ["Déjà vu","Superstition","Traffic jam","Queue jumper","Lost luggage","Rainy day","Spring clean",
        "Time zone","Leap year","Full moon","Rush hour","Paper cut","Brain freeze","Butterflies","Goosebumps",
        "Alarm clock","Snooze button","To-do list","Small talk","Wrong number","Double booking","Autocorrect fail",
        "Flat tyre","Missing sock","Dead phone","Spilt coffee","Long weekend","Public holiday","Group photo",
        "Awkward hug"],
      DRAW:   ["A lighthouse","A hot air balloon","A windmill","A treasure map","A telescope","A pyramid",
        "A castle","A bridge","A train","A submarine","A rocket","A parachute","An anchor","A compass",
        "An hourglass","A key","A crown","A ladder","A chessboard","A globe","An umbrella","A campfire","A tent",
        "A canoe","A volcano","A rainbow","A snowflake","A cactus","A palm tree","A shopping trolley"],
  }),

  ];
})();
