// Word Smash — built-in deck library.
// Each card is one word tagged with a board category:
//   { badge: "OBJECT" | "NATURE" | "ACTION" | "PERSON" | "WORLD" | "RANDOM" | "DRAW", title: "..." }
// The board decides the category, then the app pulls a word of that category.
//
// A full 48-space game runs ~40 turns. Those turns are spread over 7 categories,
// so each category comes up ~6 times, and at ~6 cards a turn that is ~40 cards
// drawn FROM ONE CATEGORY in a single game. At 30 a category the pool ran dry
// mid-game and started dealing repeats — which is exactly what happened in play.
// Expanded decks carry 100 a category (700 a deck), so a whole game uses under
// half the pool and never repeats. Decks still at 30 are flagged in the README.
//
// Works fully offline: no AI key, no Worker.
window.BUILTIN_DECKS = (function () {

  // Compact helper: build cards from a {CATEGORY: [words]} map. `more` is a
  // second map of the same shape — the decks were 30 a category and a single
  // full game burns about 40 of one, so a family game kept serving the same
  // Action cards twice. Split in two only to keep the blocks readable; the
  // pool is shuffled per game so it makes no difference to play.
  function deck(title, audience, icon, blurb, map, more) {
    const cards = [];
    const add = m => Object.keys(m).forEach(cat => m[cat].forEach(w => cards.push({ badge: cat, title: w })));
    add(map);
    if (more) add(more);
    return { game: "wordsmash", title, audience, icon, blurb, cards };
  }

  return [
  deck("80s & 90s Nostalgia", "adults (clean)", "cassette",
    "Walkmans, mullets and Saturday morning telly. The stuff everyone who grew up then still remembers.", {
      OBJECT: ["Walkman","VHS tape","Rubik's Cube","Game Boy","Tamagotchi","Floppy disk","Boombox","Nokia 3310",
        "Polaroid camera","Cassette","Pager","Discman","Fax machine","Dial-up modem","Zip drive",
        "Overhead projector","Rotary phone","Answering machine","Betamax","Laser disc","Slinky","View-Master",
        "Etch A Sketch","Speak & Spell","Casio watch","Filofax","Trapper Keeper","Lava lamp","Waterbed","Bum bag"],
      NATURE: ["Ozone layer","Halley's Comet","Acid rain","Great white shark","El Niño","Thunderstorm","Rainforest",
        "Coral reef","Bushfire","Dolly the sheep","Killer bees","Mount St Helens","Solar eclipse","Rainbow",
        "Quicksand","Glacier","Tornado","Amazon river","Sand dune","Meteor shower","Volcano","Tidal wave",
        "Blizzard","Locust swarm","Panda","Bald eagle","Redwood tree","Venus flytrap","Northern lights","Hurricane"],
      ACTION: ["Moonwalk","Breakdance","Rollerblade","Headbang","Air guitar","Macarena","Mosh pit","Aerobics",
        "Dial-up","Mixtape making","Rewinding a tape","Blowing a cartridge","Channel surfing","Passing notes",
        "Prank calling","Skateboarding","Roller disco","Bungee jumping","Line dancing","Crimping hair",
        "Renting a video","Taping the radio","Playing pinball","Slam dunking","Hacky sack","Yo-yo tricks",
        "Doing the worm","High-fiving","Grunge moshing","Speed dialling"],
      PERSON: ["Michael Jackson","Madonna","Freddie Mercury","Kurt Cobain","Princess Diana","Mr T","Spice Girls",
        "Britney Spears","Hulk Hogan","Prince","Whitney Houston","Tupac","David Hasselhoff","Macaulay Culkin",
        "Michael J Fox","Arnold Schwarzenegger","Sylvester Stallone","Tom Cruise","Julia Roberts","Jim Carrey",
        "Eddie Murphy","Will Smith","Oprah Winfrey","Michael Jordan","Mike Tyson","George Michael",
        "Cyndi Lauper","Bon Jovi","Axl Rose","Vanilla Ice"],
      WORLD:  ["Berlin Wall","Hollywood","Chernobyl","Times Square","Route 66","Silicon Valley","Video arcade","East Berlin",
        "Moscow","Hong Kong","Seattle","Roller rink","Las Vegas","Woodstock","Graceland","Beverly Hills","Bronx",
        "Tokyo","Drive-in cinema","Video store","Internet cafe","Bermuda Triangle","Phone box","Studio 54","Wall Street","Milk bar",
        "Cape Canaveral","Soviet Union","Twin Towers","Area 51"],
      RANDOM: ["Mullet","Shoulder pads","Scrunchie","Pogs","Slap bracelet","Frosted tips","Fanny pack",
        "Leg warmers","Beanie Baby","Perm","Parachute pants","Neon windbreaker","Doc Martens","Chokers","Overalls",
        "Bucket hat","Shell suit","Stonewash jeans","Jelly shoes","Snap bracelet","Furby","Troll doll","Pet rock",
        "Magic Eye","Chain wallet","Butterfly clips","Platform sneakers","Puka shells","Body glitter","Baggy jeans"],
      DRAW:   ["A DeLorean","Pac-Man","A ghetto blaster","Neon sunglasses","A skateboard","A cassette tape",
        "Space Invaders","A Ninja Turtle","A Tamagotchi","A boombox on a shoulder","A rubik's cube","A Game Boy",
        "A floppy disk","A shell suit","A mullet","A brick phone","A jukebox","A roller skate","A lava lamp",
        "A yo-yo","A bum bag","A Furby","A pager","A slap bracelet","An arcade machine","A VHS tape",
        "A skateboard ramp","A pair of Doc Martens","A cassette player","A disco ball"],
  }, {
      OBJECT: ["Atari joystick","Super Nintendo","Sega Mega Drive","Walkie talkie","CD player","Minidisc",
        "Camcorder","Typewriter","Rolodex","Beeper","Car phone","Cordless phone","TV aerial","Rabbit ears",
        "Video rewinder","Blank tape","Mixtape case","Record player","8-track","Pocket calculator",
        "Digital watch","Slap band","Hair crimper","Curling wand","Scrunchie tin","Trapper folder",
        "Lunch tin","Thermos flask","Roller skates","Skate key","Water pistol","Nerf gun","Pogo stick",
        "Hula hoop","Marble bag","Pog slammer","Sticker album","Swap card","Autograph book","Diary with a lock",
        "Cassette adapter","Cigarette lighter adapter","Steering wheel cover","Fluffy dice","Beaded seat cover",
        "Sun visor","Portable TV","Antenna booster","Remote with a dial","Channel knob","Screen wipe",
        "Floppy case","Mouse ball","Dot matrix printer","Green screen monitor","Modem cable","Phone cord",
        "Answering tape","Address book","Filofax insert","Pencil case","Correction fluid","Ink eraser",
        "Overhead sheet","Chalk duster","Blackboard","Ruler with a groove","Protractor","Compass set",
        "Homework diary"],
      NATURE: ["Comet Hale-Bopp","Hole in the ozone","Greenhouse effect","Rainforest logging","Whale watching",
        "Tasmanian tiger","Bengal tiger","Snow leopard","Black rhino","Sea turtle","Manatee","Condor",
        "Peregrine falcon","Grizzly bear","Polar bear","Emperor penguin","Blue whale","Orca","Manta ray",
        "Hammerhead","Barracuda","Piranha","Anaconda","Komodo dragon","Chameleon","Poison dart frog",
        "Praying mantis","Stick insect","Monarch butterfly","Firefly","Glow worm","Sea anemone","Starfish",
        "Sea urchin","Kelp forest","Mangrove","Cactus flower","Baobab","Sequoia","Bonsai","Bamboo grove",
        "Tumbleweed","Dust storm","Heat haze","Mirage","Ice storm","Hailstone","Frostbite","Whirlwind",
        "Waterspout","Sinkhole","Mudslide","Lava flow","Ash cloud","Geyser","Hot spring","Salt lake",
        "Coral bleaching","Algae bloom","Red tide","Sand bar","Rock pool","Estuary","Marsh","Peat bog",
        "Prairie","Steppe","Oasis","Ice shelf","Permafrost"],
      RANDOM: ["Grunge","Rave","Hip hop","New wave","Punk","Goth","Preppy","Skater","Surfer","Raver",
        "Mixtape swap","Chain letter","Pen pal","Sleepover","Roller disco","School disco","Formal",
        "Yearbook","Class photo","Detention","Tuckshop","Canteen line","Show bag","Fete","Fun run",
        "Bake sale","Car boot sale","Garage sale","Jumble sale","Lucky dip","Raffle ticket","Scratchie",
        "Lotto numbers","Chain wallet chain","Shell necklace","Friendship bracelet","Mood ring","Temporary tattoo",
        "Butterfly hair clip","Hair mascara","Glitter gel","Lip smacker","Body spray","Hair gel","Frosted lipstick",
        "Blue eyeshadow","Stick-on nails","Toe socks","Jelly sandals","Windcheater","Tracksuit pants","Denim jacket",
        "Acid wash","Tie dye","Flannel shirt","Combat boots","Platform shoes","High tops","Sweatband",
        "Bandana","Snapback","Visor","Belly chain","Cargo shorts","Board shorts","Bike shorts","Leotard",
        "Legwarmer","Puffy vest","Bomber jacket"],
      ACTION: ["Moonwalking","Breakdancing","Robot dancing","Headbanging","Air drumming","Lip syncing",
        "Roller skating","Rollerblading","Skateboarding a ramp","BMX jumping","Pogo jumping","Hula hooping",
        "Skipping rope","Hopscotching","Playing marbles","Flicking pogs","Trading cards","Swapping stickers",
        "Blowing bubblegum","Chewing gum loudly","Slurping a thickshake","Eating a paddle pop","Winding a cassette",
        "Ejecting a tape","Adjusting an aerial","Thumping the telly","Dialling a rotary phone","Hanging up a receiver",
        "Leaving a voicemail","Checking a pager","Winding a watch","Setting an alarm clock","Snoozing an alarm",
        "Ironing a shirt","Crimping hair with tongs","Backcombing hair","Spraying hairspray","Applying lip gloss",
        "Blowing a kiss","Waving goodbye","Giving a thumbs up","Doing jazz hands","Flexing a bicep","Arm wrestling",
        "Thumb wrestling","Playing rock paper scissors","Doing a high five","Fist bumping","Doing the running man",
        "Doing the sprinkler","Doing the cabbage patch","Body popping","Beatboxing","Air punching","Jumping for joy",
        "Sliding on socks","Bouncing on a bed","Building a blanket fort","Reading under the covers",
        "Torch under the doona","Playing hide and seek","Playing tag","Playing elastics","Doing a cartwheel",
        "Doing a handstand","Piggybacking","Wheelbarrow racing","Three-legged racing","Egg and spoon racing",
        "Sack racing"],
      PERSON: ["Bruce Springsteen","Cher","Tina Turner","Elton John","George Harrison","Ringo Starr","Bono",
        "Sting","Phil Collins","Rod Stewart","Billy Idol","Joan Jett","Debbie Harry","Annie Lennox","Boy George",
        "Grace Jones","Janet Jackson","Lionel Richie","Diana Ross","Stevie Nicks","Bryan Adams","Bon Scott",
        "Angus Young","Ozzy Osbourne","Alice Cooper","Meat Loaf","Kenny Rogers","Willie Nelson","Johnny Rotten",
        "Sid Vicious","Harrison Ford","Sean Connery","Roger Moore","Clint Eastwood","Bruce Willis","Mel Gibson",
        "Kevin Costner","Patrick Swayze","Demi Moore","Meg Ryan","Sandra Bullock","Winona Ryder","Drew Barrymore",
        "Whoopi Goldberg","Robin Williams","Steve Martin","John Candy","Chevy Chase","Dan Aykroyd","Bill Murray",
        "Michael Caine","Anthony Hopkins","Jodie Foster","Kathleen Turner","Michelle Pfeiffer","Kim Basinger",
        "Molly Ringwald","Emilio Estevez","Judd Nelson","Rob Lowe","Andrew McCarthy","Corey Feldman","River Phoenix",
        "Christian Slater","Keanu Reeves","Alicia Silverstone","Neve Campbell","Jennifer Aniston","Courteney Cox",
        "David Schwimmer"],
      WORLD:  ["Berlin","Prague","Budapest","Warsaw","Leningrad","Kremlin","Red Square","Checkpoint Charlie",
        "Iron Curtain","Cold War border","Cape Town","Johannesburg","Beijing","Tiananmen Square","Shanghai",
        "Seoul","Bangkok","Manila","Jakarta","Bombay","Calcutta","Karachi","Tehran","Baghdad","Kuwait City",
        "Jerusalem","Cairo","Nairobi","Lagos","Casablanca","Rio de Janeiro","Buenos Aires","Santiago","Lima",
        "Bogota","Havana","Kingston","Miami","New Orleans","Detroit","Chicago","Boston","Philadelphia","Atlanta",
        "Dallas","Houston","Denver","Phoenix","San Francisco","Los Angeles","San Diego","Portland","Vancouver",
        "Toronto","Montreal","Reykjavik","Dublin","Belfast","Glasgow","Manchester","Liverpool","Birmingham",
        "Amsterdam","Brussels","Copenhagen","Stockholm","Oslo","Helsinki","Vienna","Zurich"],
      DRAW:   ["A Walkman","A cassette single","A CD","A Discman","A payphone","A phone booth","A car phone",
        "A pager on a belt","A fax machine","A dot matrix printer","A computer mouse","A joystick","An Atari",
        "A Super Nintendo","A Sega controller","A TV with an aerial","A remote control","A VCR","A camcorder",
        "A Polaroid photo","A film canister","A View-Master","An Etch A Sketch","A Speak & Spell","A Simon game",
        "A Rubik's snake","A Slinky","A Koosh ball","A Nerf gun","A water pistol","A pogo stick","A hula hoop",
        "A skipping rope","A hopscotch grid","A marble","A pog","A sticker sheet","A swap card","A friendship bracelet",
        "A mood ring","A slap band","A scrunchie","A hair crimper","A can of hairspray","A pair of leg warmers",
        "A shell suit jacket","A denim jacket","A tie dye shirt","A flannel shirt","A pair of high tops",
        "A pair of jelly shoes","A bum bag on a hip","A chain wallet","A bandana","A sweatband","A tracksuit",
        "A boombox","A ghetto blaster on a shoulder","A record player","A vinyl sleeve","A neon sign",
        "A waterbed","A beanbag","A disco floor","A roller rink","An arcade cabinet","A pinball machine",
        "A drive-in screen","A phone with a cord","A shoulder pad"],
  }),

  deck("Aussie Everything", "family friendly", "aus",
    "Eskies, magpies and the backyard barbie. Home ground advantage for anyone who grew up here.", {
      OBJECT: ["Esky","Hills Hoist","Meat pie","Boomerang","Thongs","Zinc stick","Ute","Goon bag","Cricket bat",
        "Surfboard","Akubra","Ugg boots","Stubby holder","Bottle opener","Wheelie bin","Clothesline peg",
        "Beach towel","Zooper Dooper","Milk crate","Tinnie","Fishing rod","Barbecue tongs","Camp chair","Swag",
        "Fly screen","Sunscreen","Beach cricket set","Cattle dog lead","Water tank","Letterbox"],
      NATURE: ["Koala","Kangaroo","Platypus","Kookaburra","Redback spider","Wombat","Echidna","Magpie",
        "Great Barrier Reef","Blue-ringed octopus","Emu","Dingo","Cockatoo","Possum","Goanna","Quokka",
        "Tasmanian devil","Bottlebrush","Wattle","Gum tree","Cane toad","Crocodile","Stingray","Frilled lizard",
        "Bilby","Numbat","Lorikeet","Jellyfish","Bull ant","Sugar glider"],
      ACTION: ["Barbie","Surfing","Backyard cricket","Chuck a sickie","Bushwalk","Sausage sizzle","Swooping",
        "Shoey","Catching a wave","Snag flipping","Watching the footy","Doing a lap","Having a squiz",
        "Slip slop slap","Camping","Fishing off the jetty","Footy tipping","Chucking a uey","Rocking up",
        "Knocking off","Ducking out","Beach cricket","Bushfire watching","Riding a scooter","Popping to the shops",
        "Firing up the barbie","Cracking a tinnie","Hanging washing","Feeding the chooks","Mowing the lawn"],
      PERSON: ["Steve Irwin","Ned Kelly","Cathy Freeman","Don Bradman","Kylie Minogue","John Howard","Paul Hogan",
        "The Wiggles","Hugh Jackman","Barry Humphries","Shane Warne","Ash Barty","Ricky Ponting","Bindi Irwin",
        "Nick Cave","Missy Higgins","Adam Goodes","Nicole Kidman","Chris Hemsworth","Margot Robbie",
        "Russell Crowe","Rebel Wilson","Bob Hawke","Julia Gillard","John Farnham","Jimmy Barnes",
        "Olivia Newton-John","Rod Laver","Greg Norman","Banjo Paterson"],
      WORLD:  ["Uluru","Bondi Beach","Sydney Opera House","Great Ocean Road","Gold Coast","Outback",
        "Blue Mountains","Melbourne laneway","Kakadu","Twelve Apostles","Harbour Bridge","Byron Bay","Cairns",
        "Perth","Adelaide","Darwin","Tasmania","Fraser Island","Kangaroo Island","Snowy Mountains","Alice Springs",
        "Margaret River","Whitsundays","Barossa Valley","Port Douglas","MCG","Nullarbor","Daintree","Broome",
        "Coober Pedy"],
      RANDOM: ["Vegemite","Fairy bread","Lamington","Tim Tam","Servo pie","Milk bar","Sunnies","Arvo","Servo",
        "Bottle-o","Chook","Ute muster","Bogan","Cossie","Doona","Op shop","Ripper","Fair dinkum","She'll be right",
        "Yeah nah","Cane toad race","Meat raffle","Snag sandwich","Sausage in bread","Two-up","Melbourne Cup",
        "Boxing Day Test","Schoolies","Straya Day","Footy finals"],
      DRAW:   ["A kangaroo","A meat pie","A Hills Hoist","A surfboard","A boomerang","An esky","A koala in a tree",
        "A pair of thongs","A ute","A magpie swooping","The Opera House","Ayers Rock at sunset","A lamington",
        "A Tim Tam","A cricket bat","A wombat","A platypus","A bin chicken","A barbie","A swag",
        "The Harbour Bridge","A kookaburra","A Vegemite jar","A stubby holder","A cane toad","A shark warning sign",
        "A beach umbrella","A campfire","A cattle dog","A road train"],
  }, {
      OBJECT: ["Zooper Dooper stick","Chiko roll","Sausage sizzle tongs","Bug catcher","Fly swat","Mozzie coil",
        "Citronella candle","Beach shelter","Boogie board","Snorkel","Cricket stumps","Cricket ball","Footy",
        "Netball","Rugby ball","Golf buggy","Bait bucket","Crab pot","Yabby net","Tackle box","Boat trailer",
        "Jerry can","Roof rack","Bull bar","Snorkel on a four wheel drive","Sand flag","Beach buggy","Quad bike",
        "Whipper snipper","Lawn mower","Garden hose","Sprinkler","Rainwater tank","Solar panel","Ceiling fan",
        "Flyscreen door","Security screen","Verandah post","Colorbond fence","Paling fence","Letterbox on a post",
        "Wheelie bin lid","Recycling bin","Compost bin","Clothes hoist","Peg basket","Laundry trough","Sink tidy",
        "Kettle cord","Toastie maker","Sandwich press","Slow cooker","Camp oven","Billy can","Enamel mug",
        "Tin plate","Folding table","Picnic rug","Beach towel rack","Sunscreen tube","Zinc tube","Wide brim hat",
        "Fly veil","Work boots","High vis vest","Hard hat","Tool belt","Ute tray","Tow ball","Number plate"],
      NATURE: ["Wallaby","Bandicoot","Bilby burrow","Pademelon","Potoroo","Antechinus","Flying fox","Fruit bat",
        "Microbat","Brushtail possum","Ringtail possum","Feathertail glider","Squirrel glider","Rock wallaby",
        "Tree kangaroo","Cassowary","Brolga","Jabiru","Ibis","Pelican","Black swan","Wood duck","Willie wagtail",
        "Blue wren","Rosella","Galah","Corella","Sulphur crested cockatoo","Rainbow lorikeet","Honeyeater",
        "Currawong","Butcherbird","Whipbird","Bowerbird","Lyrebird tail","Emu chick","Malleefowl","Wedge-tailed eagle",
        "Sea eagle","Osprey","Barn owl","Tawny frogmouth","Boobook","Carpet python","Brown snake","Tiger snake",
        "Death adder","Taipan","Blue tongue lizard","Thorny devil","Bearded dragon","Water dragon","Skink",
        "Green tree frog","Corroboree frog","Bull shark","Whale shark","Grey nurse","Dugong","Humpback",
        "Sea dragon","Clownfish","Coral polyp","Giant clam","Spinifex","Saltbush","Paperbark","Ghost gum",
        "Banksia","Waratah"],
      RANDOM: ["Barbie sauce","Dead horse","Cuppa","Cold one","Coldie","Middy","Schooner","Pot of beer","Slab",
        "Six pack","Bottle shop","Drive through bottle-o","Servo coffee","Servo dog","Sausage roll","Party pie",
        "Potato scallop","Dim sim","Battered sav","Hot chips","Chicken salt","Gravy roll","Iced coffee","Milo",
        "Weet-Bix","Golden Gaytime","Bubble o Bill","Paddle Pop","Splice","Icy pole","Musk stick","Freddo",
        "Caramello Koala","Minties","Jaffas","Redskin","Wagon Wheel","Iced VoVo","Monte Carlo","Scotch Finger",
        "Anzac biscuit","Pavlova","Damper","Chiko","Dagwood dog","Show bag","Sideshow alley","Country show",
        "B&S ball","Bush dance","Backyard cricket rules","Tip and run","Six and out","One hand one bounce",
        "Nicko","Sanga","Barbie chat","Smoko","Knock off time","Sickie","Long weekend","Public holiday",
        "Australia Day lamb ad","Boxing Day sales","Anzac dawn service","Melbourne Cup sweep","Footy tipping comp",
        "Meat tray","Chook raffle","Bogan bingo"],
      ACTION: ["Throwing a boomerang","Flipping a snag","Shucking an oyster","Cracking a coldie","Sinking a tinnie",
        "Lighting the barbie","Turning the sausages","Buttering bread for a sanga","Squeezing sauce",
        "Slapping on sunscreen","Rubbing in zinc","Jamming on a hat","Swatting a fly","Slapping a mozzie",
        "Shooing a magpie","Ducking a swoop","Waving away flies","Hanging out the washing","Bringing in the washing",
        "Pegging out a doona","Winding the Hills Hoist","Mowing the nature strip","Whipper snipping","Hosing the drive",
        "Watering the garden","Filling the pool","Skimming the pool","Chlorinating the pool","Bombing into the pool",
        "Doing a dive bomb","Belly flopping","Duck diving","Paddling out","Dropping in on a wave","Wiping out",
        "Waxing a board","Rinsing off sand","Shaking out a towel","Setting up a beach shelter","Digging a sandcastle",
        "Burying someone in sand","Rock pooling","Throwing a line in","Reeling in a fish","Netting a yabby","Riding a wave in",
        "Baiting a hook","Gutting a fish","Lighting a campfire","Boiling the billy","Toasting marshmallows",
        "Rolling out a swag","Pitching a tent","Packing the ute","Strapping down a load","Checking the tyres",
        "Reversing a trailer","Doing a burnout","Bogging the car","Winching out of mud","Opening a farm gate",
        "Rounding up sheep","Shearing a sheep","Scattering chook feed","Collecting eggs","Milking a cow",
        "Cracking a whip","Riding a horse","Cutting firewood","Splitting logs"],
      PERSON: ["Steve Waugh","Mark Waugh","Glenn McGrath","Adam Gilchrist","Michael Clarke",
        "Pat Cummins","Steve Smith","David Warner","Meg Lanning","Alyssa Healy","Belinda Clark","Ian Chappell",
        "Allan Border","Dennis Lillee","Merv Hughes","Mark Taylor","Bill Lawry","Richie Benaud","Peter Brock",
        "Dick Johnson","Craig Lowndes","Mark Webber","Daniel Ricciardo","Casey Stoner","Mick Doohan","Mick Fanning",
        "Stephanie Gilmore","Tyler Wright","Grant Hackett","Kieren Perkins","Susie O'Neill","Dawn Fraser",
        "Shane Gould","Libby Trickett","Sally Fitzgibbons","Anna Meares","Sam Stosur","Pat Rafter","John Newcombe",
        "Evonne Goolagong","Lauren Jackson","Andrew Gaze","Buddy Franklin","Wayne Carey","Leigh Matthews",
        "Ron Barassi","Johnathan Thurston","Cameron Smith","Mal Meninga","Andrew Johns","Darren Lockyer",
        "Tim Cahill","Harry Kewell","Mark Viduka","Mark Schwarzer","Eddie Mabo","Fred Hollows","Howard Florey",
        "Albert Namatjira","Henry Lawson","Dorothea Mackellar","Sidney Nolan","Slim Dusty","Peter Allen",
        "Cold Chisel","Midnight Oil","Crowded House","Silverchair","Powderfinger","Tame Impala"],
      WORLD:  ["Brisbane","Canberra","Hobart","Newcastle","Wollongong","Geelong","Ballarat","Bendigo","Toowoomba",
        "Townsville","Rockhampton","Mackay","Bundaberg","Noosa","Surfers Paradise","Coolangatta","Ballina",
        "Coffs Harbour","Port Macquarie","Newcastle beach","Central Coast","Manly","Cronulla","Palm Beach",
        "Bells Beach","Torquay","Lorne","Apollo Bay","Phillip Island","Mornington Peninsula","Yarra Valley",
        "Grampians","Wilsons Promontory","Great Dividing Range","Snowy River","Murray River","Darling River",
        "Lake Eyre","Simpson Desert","Kimberley","Bungle Bungles","Karijini","Ningaloo Reef","Shark Bay",
        "Rottnest Island","Margaret River caves","Esperance","Kalgoorlie","Port Hedland","Katherine Gorge",
        "Litchfield","Tiwi Islands","Arnhem Land","Cape York","Torres Strait","Whitehaven Beach","Magnetic Island",
        "Lady Elliot Island","Lord Howe Island","Cradle Mountain","Wineglass Bay","Port Arthur","Salamanca",
        "Freycinet","Bruny Island","Flinders Ranges","Barossa","Coonawarra","Fleurieu Peninsula","Kangaroo Valley"],
      DRAW:   ["A goanna","A frilled lizard","A dingo","A bilby","A quokka","A cassowary","A pelican","A galah",
        "A cockatoo","A rosella","An emu","A crocodile","A blue tongue lizard","A huntsman spider","A redback",
        "A jellyfish","A stingray","A dugong","A whale tail","A shark fin","A gum leaf","A wattle branch",
        "A bottlebrush","A banksia","A waratah","A ghost gum","A billabong","A waterhole","A red dirt road",
        "A cattle grid","A farm gate","A windmill on a farm","A water tank","A shearing shed",
        "A hay bale","A tractor","A quad bike","A four wheel drive","A boat on a trailer","A tinnie","A jetty","A stock crate",
        "A fishing rod","A crab pot","A yabby","A prawn","An oyster","A meat tray","A sausage on bread",
        "A pie with sauce","A Chiko roll","A dagwood dog","A pav with cream","A lamington on a plate",
        "An Anzac biscuit","A Vegemite sandwich","A Milo tin","A Weet-Bix box","A thermos","A camp oven",
        "A billy on a fire","A swag rolled up","A tent","A beach shelter","A boogie board","A zinc stripe",
        "A wide brim hat","A pair of work boots","A high vis vest","A Southern Cross"],
  }),

  deck("Kids Zone", "family friendly", "balloon",
    "Simple, friendly words the whole table can shout out. Nothing anyone needs explaining.", {
      OBJECT: ["Teddy bear","Skateboard","Balloon","Backpack","Crayon","Bicycle","Kite","Lunchbox","Torch",
        "Skipping rope","Bucket","Spade","Football","Puzzle","Marble","Yo-yo","Whistle","Drum","Scooter",
        "Sandcastle","Toy car","Building block","Water pistol","Bubble wand","Paint brush","Sticker","Board game",
        "Piggy bank","Umbrella","Kaleidoscope"],
      NATURE: ["Rainbow","Butterfly","Puppy","Kitten","Snowflake","Sunflower","Ladybird","Frog","Rabbit","Duckling",
        "Tadpole","Caterpillar","Acorn","Seashell","Starfish","Penguin","Dolphin","Elephant","Giraffe","Monkey",
        "Bumblebee","Snail","Owl","Hedgehog","Squirrel","Turtle","Panda","Daisy","Pine cone","Puddle"],
      // Every one of these is something you can stand up and DO. "Building a
      // fort" was a scene, not an action, and died on its feet.
      ACTION: ["Jumping","Skipping","Splashing","Giggling","Tiptoeing","Cartwheeling","Blowing bubbles",
        "Hiding","Colouring in","Sneaking","Piggyback ride","Somersault","Clapping","Whistling",
        "Tickling","Waving","Swinging","Sliding","Hopping","Spinning","Sneezing","Yawning","Marching","Dancing",
        "Running","Rolling downhill","Blowing out a candle","Popping a balloon","Skimming a stone",
        "Climbing"],
      PERSON: ["Taylor Swift","Cristiano Ronaldo","Lionel Messi","Steve Irwin","Bindi Irwin","David Attenborough",
        "Ed Sheeran","Beyoncé","Dwayne Johnson","Serena Williams","Usain Bolt","Michael Jordan","Katy Perry",
        "Justin Bieber","Ariana Grande","Harry Styles","Adele","Bruno Mars","Billie Eilish","Dua Lipa","MrBeast",
        "Emma Watson","Daniel Radcliffe","Tom Holland","Zendaya","Simone Biles","Neil Armstrong","Albert Einstein",
        "Roald Dahl","Walt Disney"],
      WORLD:  ["Playground","Zoo","Beach","Farm","Library","Treehouse","Circus","Museum","Swimming pool","Campsite",
        "Aquarium","Toy shop","Bakery","Park","Ice rink","Castle","Lighthouse","Bus stop","Fairground",
        "Petting zoo","Forest","Cave","Island","Desert","Mountain","Rocket ship","Igloo","Windmill","Bridge",
        "Waterfall"],
      RANDOM: ["Bubble","Sprinkles","Glitter","Tickle","Wiggle","Hiccup","Freckle","Pyjamas","Bedtime story",
        "Tooth fairy","Birthday cake","Party hat","Balloon animal","Face paint","Piñata","Lemonade stand",
        "Sleepover","Hopscotch","Musical chairs","Show and tell","Silly face","Bear hug","Secret handshake",
        "Snow day","Puddle jumping","Nap time","Playdate","Dress-up box","Sandpit","Wobbly tooth"],
      DRAW:   ["A smiling sun","A rocket","A cat","A house","A rainbow","A dinosaur","A robot","An ice cream",
        "A flower","A boat","A butterfly","A snowman","A tree","A fish","A birthday cake","A hot air balloon",
        "A castle","A dog","A star","A car","A ladybird","A kite","A frog","A crown","A pirate ship","An umbrella",
        "A snail","A duck","A cupcake","A teddy bear"],
  }, {
      OBJECT: ["Wagon","Tricycle","Trampoline","Swing","Slide","Seesaw","Sandpit bucket","Beach ball","Frisbee",
        "Hula hoop","Pogo stick","Space hopper","Rocking horse","Doll","Doll house","Action figure","Toy train",
        "Train track","Race track","Remote control car","Kite string","Paper plane","Paper boat","Origami crane",
        "Colouring book","Sticker sheet","Glue stick","Safety scissors","Glitter pot","Play dough","Finger paint",
        "Chalk","Blackboard","Whiteboard","Pencil sharpener","Rubber","Exercise book","Reading book","Bookmark",
        "Night light","Lamp","Dressing gown","Slippers","Wellington boots","Raincoat","Beanie","Mittens","Scarf",
        "Swimming goggles","Armbands","Snorkel","Flippers","Surfboard","Boogie board","Bucket and spade",
        "Fishing net","Magnifying glass","Binoculars","Compass","Satchel","Water bottle","Lunch box",
        "Drink bottle","Sandwich box","Apple","Banana","Juice box","Straw","Spoon","Bowl"],
      NATURE: ["Fox cub","Wolf pup","Pony","Lamb","Calf","Piglet","Chick","Cygnet","Gosling","Bunny","Hamster",
        "Guinea pig","Goldfish","Parrot","Budgie","Canary","Peacock","Flamingo","Ostrich","Emu","Swan","Pelican",
        "Seagull","Crab","Lobster","Jellyfish","Seahorse","Octopus","Whale","Shark","Clownfish","Angelfish",
        "Lizard","Gecko","Chameleon","Tortoise","Crocodile","Hippo","Rhino","Zebra","Lion","Tiger","Cheetah",
        "Leopard","Bear","Wolf","Fox","Deer","Moose","Koala","Kangaroo","Sloth","Camel","Llama","Alpaca","Donkey",
        "Goat","Sheep","Cow","Horse","Rain","Snow","Wind","Sunshine","Cloud","Thunder","Lightning","Rock","Shell",
        "Feather"],
      RANDOM: ["Balloon pop","Party bag","Party popper","Candle","Wish","Secret","Surprise","Giggle","Whisper",
        "Shout","Tickle fight","Pillow fight","Water fight","Snowball fight","Cuddle","High five","Fist bump",
        "Thumbs up","Wink","Silly walk","Funny voice","Knock knock joke","Riddle","Rhyme","Song","Lullaby",
        "Nursery rhyme","Alphabet","Counting","Colours","Shapes","Numbers","Puzzle piece","Jigsaw","Dot to dot",
        "Maze","Spot the difference","I spy","Twenty questions","Simon says","Duck duck goose","Musical statues",
        "Pass the parcel","Pin the tail","Egg and spoon","Sack race","Three-legged race","Tug of war","Skipping game",
        "Clapping game","Hand shadow","Cartwheel","Handstand","Forward roll","Bunny hop","Star jump","Frog jump",
        "Crab walk","Bear crawl","Wobbly tooth fairy","Loose tooth","Growth chart","Report card","Gold star",
        "Sticker chart","Show bag","Lucky dip","Fancy dress","Face paint tiger","Balloon sword"],
      ACTION: ["Skipping rope","Hopscotching","Somersaulting","Cartwheeling fast","Doing a handstand",
        "Doing a forward roll","Star jumping","Bunny hopping","Frog jumping","Crab walking","Bear crawling",
        "Tiptoeing quietly","Stomping","Marching in line","Galloping","Skating","Cycling","Scootering",
        "Swimming","Floating","Diving","Splashing about","Paddling","Kicking a ball","Throwing a ball",
        "Catching a ball","Bouncing a ball","Rolling a ball","Batting","Bowling","Serving","Dribbling",
        "Juggling","Balancing","Wobbling","Falling over","Getting back up","Stretching","Touching your toes",
        "Reaching up high","Crouching down","Curling up small","Standing tall","Sitting cross-legged","Kneeling",
        "Lying down","Rolling over","Waking up","Rubbing your eyes","Brushing your teeth","Washing your hands",
        "Combing your hair","Getting dressed","Tying shoelaces","Zipping a coat","Buttoning a shirt","Packing a bag",
        "Waving goodbye","Blowing a kiss","Shaking hands","Nodding","Shaking your head","Shrugging","Pointing",
        "Counting on fingers","Whispering","Shouting","Laughing","Crying","Skipping along"],
      PERSON: ["Cristiano Ronaldo Jr","Sam Kerr","Ellyse Perry","Ash Barty","Cathy Freeman","Emma McKeon",
        "Dylan Alcott","Patty Mills","LeBron James","Stephen Curry","Neymar","Kylian Mbappe","Erling Haaland",
        "Mo Salah","Harry Kane","Megan Rapinoe","Alex Morgan","Naomi Osaka","Coco Gauff","Rafael Nadal",
        "Roger Federer","Novak Djokovic","Tiger Woods","Lewis Hamilton","Daniel Ricciardo","Valentino Rossi",
        "Michael Phelps","Ian Thorpe","Ariarne Titmus","Kaylee McKeown","Nick Kyrgios","Buddy Franklin",
        "Johnathan Thurston","Selena Gomez","Miley Cyrus","Shawn Mendes","Camila Cabello","Olivia Rodrigo",
        "Lizzo","Rihanna","Justin Timberlake","Pink","Sia","Delta Goodrem","Guy Sebastian","Keith Urban",
        "Hugh Jackman","Chris Hemsworth","Margot Robbie","Rebel Wilson","Jackie Chan","Will Smith","Tom Cruise",
        "Johnny Depp","Jim Carrey","Eddie Murphy","Robin Williams","Whoopi Goldberg","Oprah Winfrey","Ellen DeGeneres",
        "Bear Grylls","Jane Goodall","Marie Curie","Isaac Newton","Galileo","Amelia Earhart","Nelson Mandela",
        "Anne Frank","Beatrix Potter","Dr Seuss"],
      WORLD:  ["School","Classroom","Playground slide","Sports field","Gymnasium","Swimming lesson","Dance studio",
        "Music room","Art room","Science lab","Cafeteria","School bus","Corner shop","Supermarket","Post office",
        "Fire station","Police station","Hospital","Dentist","Doctor's surgery","Vet clinic","Pet shop",
        "Book shop","Toy aisle","Sweet shop","Ice cream van","Playcentre","Trampoline park","Skate park",
        "Bike track","Bowling alley","Cinema","Theatre","Puppet show","Magic show","Fun park","Ferris wheel",
        "Roller coaster","Merry-go-round","Bumper cars","Water slide","Wave pool","Splash pad","Camping ground",
        "Tent","Cabin","Caravan","Farm shed","Barn","Stable","Chicken coop","Orchard","Berry farm","Pumpkin patch",
        "Corn maze","Lighthouse hill","Rock pool","Sand dune","Jetty","Pier","Harbour","Ferry","Train station",
        "Airport","Space station","Planetarium","Dinosaur museum","Botanic garden","Butterfly house","Petting farm"],
      DRAW:   ["A smiling face","A stick figure","A family","A baby","A crown on a head","A wizard hat","A witch hat",
        "A pirate hat","A cowboy hat","A police car","A fire engine","An ambulance","A tractor","A digger",
        "A truck","A bus","A train","A plane","A helicopter","A submarine","A sailing boat","A canoe","A bicycle",
        "A scooter","A skateboard","A pair of roller skates","A ball","A bat","A goal","A trophy","A medal",
        "A drum","A guitar","A trumpet","A piano","A microphone","A book","A pencil","A paintbrush","A palette",
        "A pair of scissors","A glue stick","A backpack","A lunchbox","An apple","A banana","A pear","A carrot",
        "A slice of pizza","A hot dog","A doughnut","A lollipop","A candy cane","A gingerbread man","A snow globe",
        "A present","A bow","A balloon","A party hat","A candle on a cake","A moon","A cloud","A raindrop",
        "A snowflake","A lightning bolt","A mountain","A river","A bridge over water","A treehouse","A tent"],
  }),

  deck("Movies & TV", "adults (clean)", "clapper",
    "Blockbusters, cult classics and the shows people still quote at each other.", {
      OBJECT: ["Popcorn bucket","Film reel","Clapperboard","Remote control","3D glasses","Cinema ticket",
        "Red carpet","Oscar statue","Boom mic","Director's chair","Green screen","Movie poster","DVD box set",
        "Projector","Ticket stub","Velvet rope","Usher torch","Slushie cup","Screen curtain","Camera dolly",
        "Storyboard","Prop sword","Fake blood","Wind machine","Stunt harness","Teleprompter","Subtitle bar",
        "Rating sticker","Cinema seat","Concession stand"],
      NATURE: ["Jurassic jungle","Shark fin","King Kong's island","Twister","Desert planet","Volcano lair",
        "Haunted forest","Snowy tundra","Deep space","Ocean trench","Swamp","Savannah","Jungle vine","Cliff edge",
        "Torrential rain","Blood red sunset","Meteor strike","Iceberg","Sand storm","Canyon","Alien landscape",
        "Coral lagoon","Piranha river","Bamboo forest","Moon surface","Thunder and lightning","Wolf howl",
        "Giant eagle","Creeping fog","Cave system"],
      ACTION: ["Binge watching","Skipping the intro","Rewinding a scene","Pausing to snack","Quoting a film",
        "Booing a villain","Cheering the hero","Crying at the end","Queuing for tickets","Auditioning",
        "Method acting","Improvising","Lip syncing","Screen testing","Stunt doubling","Directing","Editing",
        "Voice acting","Spoiling the ending","Live tweeting","Arguing about the ending","Walking the red carpet",
        "Taking a bow","Applauding","Sneaking snacks in","Reading subtitles","Filming a montage",
        "Rolling the credits","Rating a film","Sitting through the credits"],
      PERSON: ["Tom Hanks","Meryl Streep","Leonardo DiCaprio","Denzel Washington","Julia Roberts",
        "Steven Spielberg","Quentin Tarantino","Morgan Freeman","Robert De Niro","Al Pacino","Samuel L Jackson",
        "Scarlett Johansson","Brad Pitt","Angelina Jolie","Will Smith","Jennifer Aniston","Robin Williams",
        "Jim Carrey","Eddie Murphy","Arnold Schwarzenegger","Keanu Reeves","Cate Blanchett","Oprah Winfrey",
        "Ricky Gervais","Steve Carell","Bryan Cranston","Tom Cruise","Harrison Ford","Anthony Hopkins",
        "Charlie Chaplin"],
      WORLD:  ["Hogwarts","Middle-earth","Gotham City","Jurassic Park","The Shire","Wakanda","Hill Valley",
        "Springfield","Westeros","Pandora","Narnia","Neverland","Oz","Death Star","Bikini Bottom","Mordor",
        "The Matrix","Tatooine","Hollywood Boulevard","Sunnydale","Bedrock","Duckburg","Metropolis","Atlantis",
        "Isla Nublar","Arrakis","The Upside Down","Stars Hollow","Amity Island","Zootopia"],
      RANDOM: ["Sequel","Reboot","Cameo","Blooper","Cliff-hanger","Spin-off","Binge","Trailer","Post-credits scene",
        "Box office","Franchise","Fan theory","Season finale","Pilot episode","Streaming","Subtitles","Dubbing",
        "Soundtrack","Screenplay","Casting","Prequel","Anti-hero","Sidekick","Nemesis","Plot armour","Catchphrase",
        "Laugh track","Blockbuster","Award season","Cult classic"],
      DRAW:   ["A film clapperboard","Popcorn","A cinema screen","A movie camera","A red carpet","An Oscar",
        "A 3D pair of glasses","A director's chair","A ticket stub","A film reel","A lightsaber","A wizard hat",
        "A shark fin","A DeLorean","A dinosaur","A superhero cape","A crown","A spaceship","A cowboy hat","A ring",
        "A haunted house","A pirate flag","A robot","A detective magnifier","A microphone","A boom mic",
        "A projector","A drive-in screen","A movie poster","A theatre curtain"],
  }),

  deck("Sports Legends", "teens", "trophy",
    "Players, moments and gear from across the codes. You don't have to be a fanatic to get these.", {
      OBJECT: ["Football","Cricket bat","Tennis racquet","Boxing glove","Surfboard","Golf club","Hockey stick",
        "Basketball","Whistle","Stopwatch","Goal post","Scoreboard","Trophy","Medal","Shin pad","Mouthguard",
        "Swim goggles","Running spikes","Baseball mitt","Helmet","Skipping rope","Weight bench","Yellow card",
        "Starting block","Ski poles","Netball bib","Water bottle","Bike helmet","Dartboard","Bowling ball"],
      NATURE: ["Mountain","Ocean","Rapids","Snowfield","Sand dune","Gale","Mud","Blazing sun","Reef",
        "Alpine forest","Desert","Frozen lake","Forest","Heatwave","Fog","Ocean current","Snowstorm","Hailstorm",
        "Sea spray","Cliff","Waterfall","Glacier","Canyon","Thunderstorm","Lightning","Blizzard","Tide",
        "Headland","Rockface","Whitewater"],
      ACTION: ["Slam dunk","Home run","Hat-trick","Penalty kick","Bowled out","Try scored","Knockout",
        "Photo finish","Sprint","Tackle","Marathon","Dive","Backflip","Volley","Free throw","Lay-up","Sledging",
        "Streaking","Warming up","Cooling down","Substitution","Time out","Half time","Overtime","Extra time",
        "Lap of honour","Podium finish","Post-match interview","Coin toss","Full time whistle"],
      PERSON: ["Michael Jordan","Serena Williams","Usain Bolt","Muhammad Ali","Pelé","Cathy Freeman","Shane Warne",
        "Tiger Woods","Roger Federer","Lionel Messi","Cristiano Ronaldo","Simone Biles","Ash Barty","Don Bradman",
        "Ian Thorpe","Layne Beachley","Sally Pearson","Adam Goodes","Rafael Nadal","Lewis Hamilton",
        "Diego Maradona","Sam Kerr","Ellyse Perry","Michael Phelps","LeBron James","Ayrton Senna",
        "Dylan Alcott","Emma McKeon","Babe Ruth","Martina Navratilova"],
      WORLD:  ["Olympic stadium","Camp Nou","Wimbledon","MCG","Alpe d'Huez","Yankee Stadium","Lord's",
        "Suncorp Stadium","Flemington","Eden Park","Wembley","Old Trafford","Maracanã",
        "Madison Square Garden","Augusta","Monaco circuit","Bondi","Everest base camp","Kokoda Track",
        "Bells Beach","Rio","Tokyo","Paris","Barcelona","Sydney","Athens","Beijing","Los Angeles","Brisbane",
        "Manchester"],
      RANDOM: ["Offside","Red card","Sudden death","Underdog","Rivalry","Team jersey","Half-time orange",
        "Fantasy league","Transfer window","Draft pick","Bench warmer","Season ticket","Sportsmanship","Trash talk",
        "Comeback","Winning streak","Losing streak","Hall of fame","Record breaker","Dark horse","Home advantage",
        "Away game","Derby","Testimonial","Warm-up lap","Drug test","Injury time","Man of the match","Wooden spoon",
        "Grand slam"],
      DRAW:   ["A football","A trophy","A medal","A whistle","A goal post","A cricket bat","A tennis racquet",
        "A boxing glove","A surfboard","A basketball hoop","A running shoe","A stopwatch","A scoreboard","A podium",
        "A referee","A helmet","A bicycle","A swimming pool","A dartboard","A golf flag","A red card",
        "A skateboard","A ski slope","A finish line","A weight","A jersey","A hockey stick","A baseball mitt",
        "A pair of goggles","A racing car"],
  }),

  deck("Around the House", "family friendly", "house",
    "Everyday things hiding in plain sight, which turns out to be far harder to describe than it sounds.", {
      OBJECT: ["Kettle","Toaster","Doorbell","Coat hanger","Ironing board","Vacuum cleaner","Mop","Laundry basket",
        "Bin lid","Tea towel","Doormat","Light switch","Curtain rail","Fridge magnet","Bread bin","Chopping board",
        "Colander","Whisk","Peeler","Corkscrew","Torch","Extension cord","Smoke alarm","Sewing kit","Toolbox",
        "Spirit level","Watering can","Step ladder","Clothes peg","Dustpan"],
      NATURE: ["Houseplant","Lawn","Weeds","Compost heap","Veggie patch","Spider web","Mould","Dust",
        "Fallen leaves","Moth","Bird nest","Hedge","Rose bush","Ant","Spider","Snail","Ladybird","Earthworm",
        "Possum","Mouse","Cockroach","Fern","Ivy","Lavender","Tomato plant","Dandelion","Butterfly","Beehive",
        "Frost","Puddle"],
      ACTION: ["Vacuuming","Washing up","Hanging washing","Mowing the lawn","Taking the bins out","Making the bed",
        "Folding laundry","Dusting","Changing a bulb","Locking up","Defrosting the freezer","Unblocking the sink",
        "Watering plants","Sweeping","Ironing","Cooking dinner","Setting the table","Doing the dishes",
        "Painting a wall","Hammering a nail","Hanging a picture","Assembling flat-pack","Reading the meter",
        "Sorting recycling","Cleaning windows","Wiping benches","Feeding the pet","Scrubbing the shower",
        "Changing sheets","Putting up shelves"],
      // Broad household names rather than renovation specialists: the faces that
      // are literally in your living room every night, which keeps a thread to
      // the deck without needing 30 famous plumbers.
      PERSON: ["Martha Stewart","Marie Kondo","Scott Cam","Shaynna Blaze","Don Burke","Costa Georgiadis",
        "Johanna Griggs","Dr Harry Cooper","Karl Stefanovic","Lisa Wilkinson","Eddie McGuire","Rove McManus",
        "Hamish Blake","Andy Lee","Carrie Bickmore","Waleed Aly","Shaun Micallef","Magda Szubanski",
        "Bert Newton","Daryl Somers","Molly Meldrum","Ray Martin","Tracy Grimshaw","David Attenborough",
        "Oprah Winfrey","Bear Grylls","Gordon Ramsay","Jamie Oliver","Ellen DeGeneres","Graham Norton"],
      WORLD:  ["Kitchen","Bathroom","Garage","Attic","Basement","Backyard","Hallway","Laundry","Pantry",
        "Spare room","Front porch","Shed","Balcony","Driveway","Letterbox","Garden path","Rooftop","Staircase",
        "Cupboard under the stairs","Linen closet","Nursery","Study","Sunroom","Deck","Carport","Courtyard","Loft",
        "Cellar","Utility room","Front gate"],
      RANDOM: ["Missing sock","Junk drawer","Squeaky door","Blown fuse","Leaky tap","Loose floorboard","Spare key",
        "Odd spoon","Dead batteries","Wrong-size screw","Tangled cables","Half-used paint tin","Expired sauce",
        "Random remote","Instruction manual","Broken zip","Old phone charger","Mystery stain","Fridge leftovers",
        "Dodgy shelf","Chore roster","Shopping list","Power bill","Spare button","Rusty hinge","Sticky drawer",
        "Draughty window","Wonky table leg","Warranty card","Blunt scissors"],
      DRAW:   ["A kettle","A toaster","A vacuum cleaner","A mop and bucket","A washing machine","A front door",
        "A letterbox","A lawnmower","A ladder","A light bulb","A house plant","A garden hose","A bin",
        "A clothesline","A doormat","A tap dripping","A hammer","A screwdriver","A paint roller","A wheelbarrow",
        "A sofa","A bed","A dining table","A fridge","A shower","A staircase","A window","A chimney",
        "A garden gnome","A shed"],
  }),

  deck("Music Icons", "teens", "note",
    "Artists, instruments and the songs that get sung badly at every party.", {
      OBJECT: ["Electric guitar","Drum kit","Microphone","Vinyl record","Headphones","Keyboard","Amplifier",
        "Saxophone","Tambourine","Turntable","Guitar pick","Drum stick","Violin","Harmonica","Trumpet","Ukulele",
        "Speaker stack","Mixing desk","Setlist","Tour bus","Backstage pass","Stage light","Smoke machine","Capo",
        "Banjo","Cello","Bass guitar","Piano stool","Music stand","Metronome"],
      NATURE: ["Nightingale","Songbird","Dawn chorus","Whale song","Wolf","Cricket","Birdsong","Thunder",
        "Ocean waves","Babbling brook","Waterfall","Canyon","Cave","Howling wind","Rain","Beehive","Frog",
        "Cicada","Kookaburra","Magpie","Humpback whale","Lyrebird","Mockingbird","Canary","Cockatoo",
        "Woodpecker","Owl","Seagull","Echo","Storm"],
      ACTION: ["Headbanging","Crowd surfing","Air guitar","Singing along","Busking","Jamming","Beatboxing","DJing",
        "Moshing","Taking a bow","Sound check","Lip syncing","Freestyling","Harmonising","Whistling a tune",
        "Tapping a beat","Clapping along","Waving a lighter","Stage diving","Dropping the bass","Recording a demo",
        "Going on tour","Signing autographs","Warming up vocals","Tuning a guitar","Writing lyrics","Sampling",
        "Remixing","Conducting","Drum solo"],
      PERSON: ["Elvis Presley","The Beatles","Beyoncé","Freddie Mercury","Taylor Swift","Bob Marley","Dolly Parton",
        "Michael Jackson","Adele","Ed Sheeran","Nirvana","Queen","AC/DC","INXS","Prince","Whitney Houston",
        "David Bowie","Rihanna","Bruno Mars","Billie Eilish","Bruce Springsteen","Aretha Franklin",
        "Amy Winehouse","Johnny Cash","Bob Dylan","Jimi Hendrix","Tina Turner","Elton John","Stevie Wonder","Usher"],
      WORLD:  ["Abbey Road","Nashville","Glastonbury","Coachella","Sydney Opera House","Woodstock","Motown",
        "Broadway","Ibiza","Detroit","Liverpool","New Orleans","Memphis","Hollywood Bowl","Vienna",
        "Splendour in the Grass","Tamworth","Royal Albert Hall","Carnegie Hall","Red Rocks","Recording studio",
        "Concert hall","Music festival","Karaoke bar","Record shop","Rehearsal room","Radio station","Nightclub",
        "Busker corner","Grand Ole Opry"],
      RANDOM: ["Earworm","One-hit wonder","Album cover","Encore","Chart topper","Guilty pleasure","Karaoke",
        "Playlist","Mixtape","Fan club","Boy band","Girl group","Cover version","Duet","Riff","Chorus","Bridge",
        "Falsetto","Power ballad","Air drums","Vinyl revival","Streaming numbers","Gold record","Groupie",
        "Band merch","Festival wristband","Dad rock","Autotune","Lyric video","Support act"],
      DRAW:   ["An electric guitar","A drum kit","A microphone","A vinyl record","A pair of headphones","A piano",
        "A saxophone","A trumpet","A speaker","A DJ deck","A music note","A tambourine","A guitar pick","A violin",
        "A harmonica","A ukulele","A boombox","A stage","A tour bus","A concert crowd","A cassette",
        "A conductor's baton","A treble clef","A jukebox","A megaphone","A festival tent","A wristband",
        "A vinyl sleeve","A metronome","A karaoke machine"],
  }),

  deck("Food & Drink", "family friendly", "cup",
    "Meals, snacks and drinks. Easy to picture, surprisingly tricky to describe without saying the word.", {
      OBJECT: ["Frying pan","Wooden spoon","Rolling pin","Cheese grater","Teapot","Cutting board","Whisk",
        "Baking tray","Measuring cup","Can opener","Cocktail shaker","Salad bowl","Pepper grinder","Ice tray",
        "Lunch box","Thermos","Straw","Corkscrew","Toaster","Blender","Barbecue plate","Pizza cutter","Egg cup",
        "Mixing bowl","Ladle","Slow cooker","Coffee plunger","Sushi mat","Skewer","Apron"],
      NATURE: ["Tomato vine","Apple tree","Beehive","Wheat field","Coffee bean","Cocoa pod","Olive grove",
        "Hop field","Herb garden","Wild truffle","Lemon tree","Chilli plant","Corn field","Rice paddy",
        "Maple tree","Salt flats","Fresh water spring","Cinnamon bark","Berry bush","Pumpkin vine","Avocado tree",
        "Banana palm","Mango tree","Potato field","Strawberry patch","Grapevine","Peanut plant","Sunflower seed",
        "Fig tree","Wild mint"],
      ACTION: ["Barbecuing","Baking","Boiling","Whisking","Kneading","Marinating","Toasting","Grilling","Simmering",
        "Chopping","Peeling","Stirring","Flipping a pancake","Icing a cake","Slicing bread","Frying an egg",
        "Making a sandwich","Setting the table","Pouring a drink","Blowing on soup","Doing the dishes",
        "Ordering takeaway","Booking a table","Sharing dessert","Snacking","Meal prepping","Taste testing",
        "Seasoning","Plating up","Washing veggies"],
      PERSON: ["Gordon Ramsay","Jamie Oliver","Nigella Lawson","Julia Child","Matt Moran","Neil Perry",
        "Colin Fassnidge","Marion Grasby","Curtis Stone","Maggie Beer","Matt Preston","Anthony Bourdain",
        "Heston Blumenthal","Mary Berry","Paul Hollywood","Wolfgang Puck","Ina Garten","Guy Fieri",
        "Marco Pierre White","Rick Stein","Adriano Zumbo","Poh Ling Yeow","Manu Feildel","Ainsley Harriott",
        "Julie Goodwin","Donna Hay","Kylie Kwong","Adam Liaw","Gary Mehigan","Melissa Leong"],
      WORLD:  ["Bakery","Farmers market","Food truck","Fish and chip shop","Cafe","Vineyard","Pizzeria",
        "Ice cream parlour","Night market","Buffet","Supermarket","Butcher shop","Bistro","Beer garden",
        "Rooftop bar","Diner","Sushi train","Deli","Orchard","Brewery","Country pub","Street food stall",
        "Bakery window","Fruit stand","Cellar door","Test kitchen","Canteen","Picnic spot","Barbecue area",
        "Food hall"],
      RANDOM: ["Leftovers","Secret recipe","Food coma","Midnight snack","Doggy bag","Brunch","Side dish",
        "Comfort food","Guilty pleasure","Spice level","Recipe fail","Burnt toast","Soggy chips","Melted ice cream",
        "Fizzy drink","Second helping","Sharing platter","Dessert menu","Happy hour","Takeaway night",
        "Packed lunch","Picnic blanket","Hot sauce","Pickle jar","Cheese board","Roast dinner","Sunday lunch",
        "Street food","Meal deal","Bottomless cup"],
      DRAW:   ["A pizza slice","An ice cream cone","A burger","A cup of coffee","A birthday cake","A banana",
        "A pineapple","A hot dog","A fried egg","A cupcake","A teapot","A wine glass","A watermelon slice",
        "A bunch of grapes","A loaf of bread","A doughnut","A bowl of noodles","A taco","A milkshake",
        "A chef's hat","A frying pan","A barbecue","A picnic basket","A lollipop","A pretzel","A sushi roll",
        "A carrot","A chilli","A jar of honey","A toaster with toast"],
  }),

  deck("Adults After Dark 🔞", "adults (spicy)", "moon",
    "Rude, cheeky and firmly after bedtime. Keep this one away from the kids' table.", {
      OBJECT: ["Handcuffs","Lace lingerie","Whipped cream","Red wine","Tequila shot","Feather boa","Silk sheets",
        "Massage oil","Pole dancing pole","Blindfold","Fishnet stockings","Corset","High heels","Bar tab","Fake ID",
        "Beer bong","Playing cards","Dice cup","Karaoke mic","Neon sign","Bottle of bubbly","Cigar","Poker chips",
        "Lipstick","Little black dress","Bow tie","Champagne flute","Hip flask","Chocolate body paint","Mirror ball"],
      NATURE: ["Melons","Moonlit beach","Hot spring","Secluded waterfall","Beaver","Full moon",
        "Peach","Banana","Love birds","Rabbit","Stallion","Lioness","Snake","Peacock","Bull",
        "Coconuts","Cherry","Cucumber","Night owl","Mating season","Morning dew",
        "Tropical storm","Steamy jungle","Volcano heat","Deserted cove","Pussy willow","Starry night",
        "Birds and the bees","Eggplant","Heatwave"],
      ACTION: ["Flirting","Skinny dipping","Pub crawl","Strip poker","Speed dating","Sliding into DMs","Ghosting",
        "Swiping right","Hangover","Walk of shame","Truth or dare","Spin the bottle","Body shot",
        "Shotgunning a beer","Karaoke duet","Last orders","Cheeky snog","Chatting someone up","Blind date",
        "Beer pong","Dad dancing","Kicking on","Big night out","Sneaking out","Making eyes","Late-night kebab",
        "Hair of the dog","Boozy brunch","Bar hopping","Nightcap"],
      PERSON: ["Marilyn Monroe","Hugh Hefner","Bettie Page","Brigitte Bardot","Sophia Loren","Raquel Welch",
        "Farrah Fawcett","Elizabeth Taylor","Mae West","Casanova","Cleopatra","Errol Flynn","Madonna","Cher",
        "Dita Von Teese","Lady Gaga","Mick Jagger","Barry White","Tom Jones","Prince","Rod Stewart",
        "Warren Beatty","George Clooney","Fabio","Pamela Anderson","Paris Hilton","Kim Kardashian",
        "Jennifer Lopez","Shakira","Russell Brand"],
      WORLD:  ["Las Vegas","Amsterdam","Ibiza","Nightclub","Strip club","Casino","Honeymoon suite","Kings Cross",
        "Rio carnival","Bourbon Street","Bali","Magaluf","Monte Carlo","Speakeasy","Hotel bar","Hotel jacuzzi",
        "Cruise ship","Bachelor pad","Love hotel","Red light district","Bangkok","New Orleans","Berlin club",
        "Vegas chapel","Beach club","Penthouse","Dive bar","Cabaret","Burlesque show","Pool party"],
      RANDOM: ["Hickey","Dad bod","Beer goggles","Netflix and chill","Booty call","Wingman rules","Bad tattoo",
        "Regrettable text","Dirty martini","Hangxiety","Ex's new partner","Love bite","Bar tab shock","Morning after",
        "Drunk dial","Slurred speech","Kebab shop queue","Sneaky pash","Cheeky Nando's","Last drinks",
        "Awkward silence","Flirty emoji","Red flag","Green flag","Situationship","Rebound","Dating app bio",
        "Group chat gossip","Wedding speech","Bad chat-up line"],
      DRAW:   ["A cocktail","A pair of handcuffs","A pair of high heels","A love heart","A wine glass",
        "A disco ball","A pair of lips","A neon sign","A bottle of champagne","A pair of dice","A poker hand",
        "A martini","A bow tie","A lipstick","A rose","A candle","A hot tub","A bed","A cocktail umbrella",
        "A shot glass","A leather jacket","A tattoo","A key to a hotel room","A do not disturb sign","A moon",
        "A cigar","A limousine","A microphone stand","A love letter","A pair of sunglasses at night"],
  }),

  deck("Classic Mixed Bag", "adults (clean)", "dice",
    "A bit of everything, so no single person at the table has the advantage.", {
      OBJECT: ["Umbrella","Wallet","Suitcase","Compass","Telescope","Hourglass","Padlock","Wheelbarrow","Anchor",
        "Ladder","Typewriter","Globe","Binoculars","Magnifying glass","Chessboard","Piano","Bicycle","Lantern",
        "Mirror","Basket","Rope","Bucket","Shovel","Broom","Candle","Camera","Newspaper","Backpack","Clock","Kite"],
      NATURE: ["Volcano","Waterfall","Glacier","Desert","Rainforest","Coral reef","Thunderstorm","Avalanche","Cave",
        "Canyon","Tornado","Earthquake","Iceberg","Sand dune","Geyser","Swamp","Meadow","Fjord","Tundra","Savannah",
        "Lightning","Eclipse","Comet","Rainbow","Tide","Monsoon","Whirlpool","Sinkhole","Delta","Reef"],
      ACTION: ["Juggling","Whistling","Tiptoeing","Yawning","Sneezing","Snoring","Shivering","Wrestling",
        "Skydiving","Hitchhiking","Camping","Fishing","Knitting","Gardening","Painting","Sculpting","Meditating",
        "Stretching","Sprinting","Swimming","Climbing","Digging","Rowing","Sailing","Cycling","Bargaining",
        "Queuing","Celebrating","Apologising","Daydreaming"],
      PERSON: ["Albert Einstein","Cleopatra","Leonardo da Vinci","Marie Curie","Nelson Mandela",
        "William Shakespeare","Amelia Earhart","Neil Armstrong","Mozart","Frida Kahlo","Isaac Newton",
        "Julius Caesar","Joan of Arc","Charles Darwin","Vincent van Gogh","Mahatma Gandhi","Queen Elizabeth",
        "Napoleon","Rosa Parks","Alexander Fleming","Abraham Lincoln","Martin Luther King Jr",
        "Winston Churchill","Beethoven","Michelangelo","Anne Frank","Florence Nightingale","Nikola Tesla",
        "Galileo","Jane Austen"],
      WORLD:  ["Eiffel Tower","Great Wall of China","Pyramids","Colosseum","Taj Mahal","Machu Picchu","Stonehenge",
        "Grand Canyon","Niagara Falls","Mount Everest","Venice","Tokyo","Cairo","Rome","Paris","Amazon rainforest",
        "Sahara","Antarctica","Iceland","Serengeti","New York","London","Istanbul","Athens","Petra","Angkor Wat",
        "Easter Island","Galápagos","Santorini","Kyoto"],
      RANDOM: ["Déjà vu","Superstition","Traffic jam","Queue jumper","Lost luggage","Rainy day","Spring clean",
        "Time zone","Leap year","Full moon","Rush hour","Paper cut","Brain freeze","Butterflies","Goosebumps",
        "Alarm clock","Snooze button","To-do list","Small talk","Wrong number","Double booking","Autocorrect fail",
        "Flat tyre","Missing sock","Dead phone","Spilt coffee","Long weekend","Public holiday","Group photo",
        "Awkward hug"],
      DRAW:   ["A lighthouse","A hot air balloon","A windmill","A treasure map","A telescope","A pyramid",
        "A castle","A bridge","A train","A submarine","A rocket","A parachute","An anchor","A compass",
        "An hourglass","A key","A crown","A ladder","A chessboard","A globe","An umbrella","A campfire","A tent",
        "A canoe","A volcano","A rainbow","A snowflake","A cactus","A palm tree","A shopping trolley"],
  }),

  ];
})();
