// Word Smash — built-in deck library.
// Each card is one word tagged with a board category:
//   { badge: "OBJECT" | "NATURE" | "ACTION" | "PERSON" | "WORLD" | "RANDOM" | "DRAW", title: "..." }
// The board decides the category, then the app pulls a word of that category.
//
// A full 48-space game runs ~40 turns. Those turns are spread over 7 categories,
// so each category comes up ~6 times, and at ~6 cards a turn that is ~40 cards
// drawn FROM ONE CATEGORY in a single game. At 30 a category the pool ran dry
// mid-game and started dealing repeats — which is exactly what happened in play.
// Expanded decks carry 100 a category (700 a deck), so a whole game uses under
// half the pool and never repeats. Decks still at 30 are flagged in the README.
//
// Works fully offline: no AI key, no Worker.
window.BUILTIN_DECKS = (function () {

  // Compact helper: build cards from a {CATEGORY: [words]} map. `more` is a
  // second map of the same shape — the decks were 30 a category and a single
  // full game burns about 40 of one, so a family game kept serving the same
  // Action cards twice. Split in two only to keep the blocks readable; the
  // pool is shuffled per game so it makes no difference to play.
  function deck(title, audience, icon, blurb, ...maps) {
    const cards = [];
    maps.forEach(m => m && Object.keys(m).forEach(cat => m[cat].forEach(w => cards.push({ badge: cat, title: w }))));
    return { game: "wordsmash", title, audience, icon, blurb, cards };
  }

  return [
  deck("80s & 90s Nostalgia", "adults (clean)", "cassette",
    "Walkmans, mullets and Saturday morning telly. The stuff everyone who grew up then still remembers.", {
      OBJECT: [
        "Walkman","VHS tape","Rubik's Cube","Game Boy","Tamagotchi","Floppy disk",
        "Boombox","Nokia 3310","Polaroid camera","Cassette","Pager","Discman",
        "Fax machine","Dial-up modem","Zip drive","Overhead projector","Rotary phone","Answering machine",
        "Betamax","Laser disc","Slinky","View-Master","Etch A Sketch","Speak & Spell",
        "Casio watch","Filofax","Trapper Keeper","Lava lamp","Waterbed","Bum bag",
        "Atari joystick","Super Nintendo","Sega Mega Drive","Walkie talkie","CD player","Minidisc",
        "Camcorder","Typewriter","Rolodex","Beeper","Car phone","Cordless phone",
        "TV aerial","Rabbit ears","Video rewinder","Blank tape","Mixtape case","Record player",
        "8-track","Pocket calculator","Digital watch","Slap band","Hair crimper","Curling wand",
        "Scrunchie tin","Trapper folder","Lunch tin","Thermos flask","Roller skates","Skate key",
        "Water pistol","Nerf gun","Pogo stick","Hula hoop","Marble bag","Pog slammer",
        "Sticker album","Swap card","Autograph book","Diary with a lock","Cassette adapter","Cigarette lighter adapter",
        "Steering wheel cover","Fluffy dice","Beaded seat cover","Sun visor","Portable TV","Antenna booster",
        "Remote with a dial","Channel knob","Screen wipe","Floppy case","Mouse ball","Dot matrix printer",
        "Green screen monitor","Modem cable","Phone cord","Answering tape","Address book","Filofax insert",
        "Pencil case","Correction fluid","Ink eraser","Overhead sheet","Chalk duster","Blackboard",
        "Ruler with a groove","Protractor","Compass set","Homework diary"],
      NATURE: [
        "Ozone layer","Halley's Comet","Acid rain","Great white shark","El Niño","Thunderstorm",
        "Rainforest","Coral reef","Bushfire","Dolly the sheep","Killer bees","Mount St Helens",
        "Solar eclipse","Rainbow","Quicksand","Glacier","Tornado","Amazon river",
        "Sand dune","Meteor shower","Volcano","Tidal wave","Blizzard","Locust swarm",
        "Panda","Bald eagle","Redwood tree","Venus flytrap","Northern lights","Hurricane",
        "Comet Hale-Bopp","Hole in the ozone","Greenhouse effect","Rainforest logging","Whale watching","Tasmanian tiger",
        "Bengal tiger","Snow leopard","Black rhino","Sea turtle","Manatee","Condor",
        "Peregrine falcon","Grizzly bear","Polar bear","Emperor penguin","Blue whale","Orca",
        "Manta ray","Hammerhead","Barracuda","Piranha","Anaconda","Komodo dragon",
        "Chameleon","Poison dart frog","Praying mantis","Stick insect","Monarch butterfly","Firefly",
        "Glow worm","Sea anemone","Starfish","Sea urchin","Kelp forest","Mangrove",
        "Cactus flower","Baobab","Sequoia","Bonsai","Bamboo grove","Tumbleweed",
        "Dust storm","Heat haze","Mirage","Ice storm","Hailstone","Frostbite",
        "Whirlwind","Waterspout","Sinkhole","Mudslide","Lava flow","Ash cloud",
        "Geyser","Hot spring","Salt lake","Coral bleaching","Algae bloom","Red tide",
        "Sand bar","Rock pool","Estuary","Marsh","Peat bog","Prairie",
        "Steppe","Oasis","Ice shelf","Permafrost"],
      ACTION: [
        "Moonwalk","Breakdance","Rollerblade","Headbang","Air guitar","Macarena",
        "Mosh pit","Aerobics","Dial-up","Mixtape making","Rewinding a tape","Blowing a cartridge",
        "Channel surfing","Passing notes","Prank calling","Skateboarding","Roller disco","Bungee jumping",
        "Line dancing","Crimping hair","Renting a video","Taping the radio","Playing pinball","Slam dunking",
        "Hacky sack","Yo-yo tricks","Doing the worm","High-fiving","Grunge moshing","Speed dialling",
        "Moonwalking","Breakdancing","Robot dancing","Headbanging","Air drumming","Lip syncing",
        "Roller skating","Rollerblading","Skateboarding a ramp","BMX jumping","Pogo jumping","Hula hooping",
        "Skipping rope","Hopscotching","Playing marbles","Flicking pogs","Trading cards","Swapping stickers",
        "Blowing bubblegum","Chewing gum loudly","Slurping a thickshake","Eating a paddle pop","Winding a cassette","Ejecting a tape",
        "Adjusting an aerial","Thumping the telly","Dialling a rotary phone","Hanging up a receiver","Leaving a voicemail","Checking a pager",
        "Winding a watch","Setting an alarm clock","Snoozing an alarm","Ironing a shirt","Crimping hair with tongs","Backcombing hair",
        "Spraying hairspray","Applying lip gloss","Blowing a kiss","Waving goodbye","Giving a thumbs up","Doing jazz hands",
        "Flexing a bicep","Arm wrestling","Thumb wrestling","Playing rock paper scissors","Doing a high five","Fist bumping",
        "Doing the running man","Doing the sprinkler","Doing the cabbage patch","Body popping","Beatboxing","Air punching",
        "Jumping for joy","Sliding on socks","Bouncing on a bed","Building a blanket fort","Reading under the covers","Torch under the doona",
        "Playing hide and seek","Playing tag","Playing elastics","Doing a cartwheel","Doing a handstand","Piggybacking",
        "Wheelbarrow racing","Three-legged racing","Egg and spoon racing","Sack racing"],
      PERSON: [
        "Michael Jackson","Madonna","Freddie Mercury","Kurt Cobain","Princess Diana","Mr T",
        "Spice Girls","Britney Spears","Hulk Hogan","Prince","Whitney Houston","Tupac",
        "David Hasselhoff","Macaulay Culkin","Michael J Fox","Arnold Schwarzenegger","Sylvester Stallone","Tom Cruise",
        "Julia Roberts","Jim Carrey","Eddie Murphy","Will Smith","Oprah Winfrey","Michael Jordan",
        "Mike Tyson","George Michael","Cyndi Lauper","Bon Jovi","Axl Rose","Vanilla Ice",
        "Bruce Springsteen","Cher","Tina Turner","Elton John","George Harrison","Ringo Starr",
        "Bono","Sting","Phil Collins","Rod Stewart","Billy Idol","Joan Jett",
        "Debbie Harry","Annie Lennox","Boy George","Grace Jones","Janet Jackson","Lionel Richie",
        "Diana Ross","Stevie Nicks","Bryan Adams","Bon Scott","Angus Young","Ozzy Osbourne",
        "Alice Cooper","Meat Loaf","Kenny Rogers","Willie Nelson","Johnny Rotten","Sid Vicious",
        "Harrison Ford","Sean Connery","Roger Moore","Clint Eastwood","Bruce Willis","Mel Gibson",
        "Kevin Costner","Patrick Swayze","Demi Moore","Meg Ryan","Sandra Bullock","Winona Ryder",
        "Drew Barrymore","Whoopi Goldberg","Robin Williams","Steve Martin","John Candy","Chevy Chase",
        "Dan Aykroyd","Bill Murray","Michael Caine","Anthony Hopkins","Jodie Foster","Kathleen Turner",
        "Michelle Pfeiffer","Kim Basinger","Molly Ringwald","Emilio Estevez","Judd Nelson","Rob Lowe",
        "Andrew McCarthy","Corey Feldman","River Phoenix","Christian Slater","Keanu Reeves","Alicia Silverstone",
        "Neve Campbell","Jennifer Aniston","Courteney Cox","David Schwimmer"],
      WORLD: [
        "Berlin Wall","Hollywood","Chernobyl","Times Square","Route 66","Silicon Valley",
        "Video arcade","East Berlin","Moscow","Hong Kong","Seattle","Roller rink",
        "Las Vegas","Woodstock","Graceland","Beverly Hills","Bronx","Tokyo",
        "Drive-in cinema","Video store","Internet cafe","Bermuda Triangle","Phone box","Studio 54",
        "Wall Street","Milk bar","Cape Canaveral","Soviet Union","Twin Towers","Area 51",
        "Berlin","Prague","Budapest","Warsaw","Leningrad","Kremlin",
        "Red Square","Checkpoint Charlie","Iron Curtain","Cold War border","Cape Town","Johannesburg",
        "Beijing","Tiananmen Square","Shanghai","Seoul","Bangkok","Manila",
        "Jakarta","Bombay","Calcutta","Karachi","Tehran","Baghdad",
        "Kuwait City","Jerusalem","Cairo","Nairobi","Lagos","Casablanca",
        "Rio de Janeiro","Buenos Aires","Santiago","Lima","Bogota","Havana",
        "Kingston","Miami","New Orleans","Detroit","Chicago","Boston",
        "Philadelphia","Atlanta","Dallas","Houston","Denver","Phoenix",
        "San Francisco","Los Angeles","San Diego","Portland","Vancouver","Toronto",
        "Montreal","Reykjavik","Dublin","Belfast","Glasgow","Manchester",
        "Liverpool","Birmingham","Amsterdam","Brussels","Copenhagen","Stockholm",
        "Oslo","Helsinki","Vienna","Zurich"],
      RANDOM: [
        "Mullet","Shoulder pads","Scrunchie","Pogs","Slap bracelet","Frosted tips",
        "Fanny pack","Leg warmers","Beanie Baby","Perm","Parachute pants","Neon windbreaker",
        "Doc Martens","Chokers","Overalls","Bucket hat","Shell suit","Stonewash jeans",
        "Jelly shoes","Snap bracelet","Furby","Troll doll","Pet rock","Magic Eye",
        "Chain wallet","Butterfly clips","Platform sneakers","Puka shells","Body glitter","Baggy jeans",
        "Grunge","Rave","Hip hop","New wave","Punk","Goth",
        "Preppy","Skater","Surfer","Raver","Mixtape swap","Chain letter",
        "Pen pal","Sleepover","Roller disco","School disco","Formal","Yearbook",
        "Class photo","Detention","Tuckshop","Canteen line","Show bag","Fete",
        "Fun run","Bake sale","Car boot sale","Garage sale","Jumble sale","Lucky dip",
        "Raffle ticket","Scratchie","Lotto numbers","Chain wallet chain","Shell necklace","Friendship bracelet",
        "Mood ring","Temporary tattoo","Butterfly hair clip","Hair mascara","Glitter gel","Lip smacker",
        "Body spray","Hair gel","Frosted lipstick","Blue eyeshadow","Stick-on nails","Toe socks",
        "Jelly sandals","Windcheater","Tracksuit pants","Denim jacket","Acid wash","Tie dye",
        "Flannel shirt","Combat boots","Platform shoes","High tops","Sweatband","Bandana",
        "Snapback","Visor","Belly chain","Cargo shorts","Board shorts","Bike shorts",
        "Leotard","Legwarmer","Puffy vest","Bomber jacket"],
      DRAW: [
        "A DeLorean","Pac-Man","A ghetto blaster","Neon sunglasses","A skateboard","A cassette tape",
        "Space Invaders","A Ninja Turtle","A Tamagotchi","A boombox on a shoulder","A rubik's cube","A Game Boy",
        "A floppy disk","A shell suit","A mullet","A brick phone","A jukebox","A roller skate",
        "A lava lamp","A yo-yo","A bum bag","A Furby","A pager","A slap bracelet",
        "An arcade machine","A VHS tape","A skateboard ramp","A pair of Doc Martens","A cassette player","A disco ball",
        "A Walkman","A cassette single","A CD","A Discman","A payphone","A phone booth",
        "A car phone","A pager on a belt","A fax machine","A dot matrix printer","A computer mouse","A joystick",
        "An Atari","A Super Nintendo","A Sega controller","A TV with an aerial","A remote control","A VCR",
        "A camcorder","A Polaroid photo","A film canister","A View-Master","An Etch A Sketch","A Speak & Spell",
        "A Simon game","A Rubik's snake","A Slinky","A Koosh ball","A Nerf gun","A water pistol",
        "A pogo stick","A hula hoop","A skipping rope","A hopscotch grid","A marble","A pog",
        "A sticker sheet","A swap card","A friendship bracelet","A mood ring","A slap band","A scrunchie",
        "A hair crimper","A can of hairspray","A pair of leg warmers","A shell suit jacket","A denim jacket","A tie dye shirt",
        "A flannel shirt","A pair of high tops","A pair of jelly shoes","A bum bag on a hip","A chain wallet","A bandana",
        "A sweatband","A tracksuit","A boombox","A ghetto blaster on a shoulder","A record player","A vinyl sleeve",
        "A neon sign","A waterbed","A beanbag","A disco floor","A roller rink","An arcade cabinet",
        "A pinball machine","A drive-in screen","A phone with a cord","A shoulder pad"],
  }, {
      OBJECT: [],
      NATURE: [],
      RANDOM: [],
      ACTION: [],
      PERSON: [],
      WORLD: [],
      DRAW: [],
  }),

  deck("Aussie Everything", "family friendly", "aus",
    "Eskies, magpies and the backyard barbie. Home ground advantage for anyone who grew up here.", {
      OBJECT: [
        "Esky","Hills Hoist","Meat pie","Boomerang","Thongs","Zinc stick",
        "Ute","Goon bag","Cricket bat","Surfboard","Akubra","Ugg boots",
        "Stubby holder","Bottle opener","Wheelie bin","Clothesline peg","Beach towel","Zooper Dooper",
        "Milk crate","Tinnie","Fishing rod","Barbecue tongs","Camp chair","Swag",
        "Fly screen","Sunscreen","Beach cricket set","Cattle dog lead","Water tank","Letterbox",
        "Zooper Dooper stick","Chiko roll","Sausage sizzle tongs","Bug catcher","Fly swat","Mozzie coil",
        "Citronella candle","Beach shelter","Boogie board","Snorkel","Cricket stumps","Cricket ball",
        "Footy","Netball","Rugby ball","Golf buggy","Bait bucket","Crab pot",
        "Yabby net","Tackle box","Boat trailer","Jerry can","Roof rack","Bull bar",
        "Snorkel on a four wheel drive","Sand flag","Beach buggy","Quad bike","Whipper snipper","Lawn mower",
        "Garden hose","Sprinkler","Rainwater tank","Solar panel","Ceiling fan","Flyscreen door",
        "Security screen","Verandah post","Colorbond fence","Paling fence","Letterbox on a post","Wheelie bin lid",
        "Recycling bin","Compost bin","Clothes hoist","Peg basket","Laundry trough","Sink tidy",
        "Kettle cord","Toastie maker","Sandwich press","Slow cooker","Camp oven","Billy can",
        "Enamel mug","Tin plate","Folding table","Picnic rug","Beach towel rack","Sunscreen tube",
        "Zinc tube","Wide brim hat","Fly veil","Work boots","High vis vest","Hard hat",
        "Tool belt","Ute tray","Tow ball","Number plate"],
      NATURE: [
        "Koala","Kangaroo","Platypus","Kookaburra","Redback spider","Wombat",
        "Echidna","Magpie","Great Barrier Reef","Blue-ringed octopus","Emu","Dingo",
        "Cockatoo","Possum","Goanna","Quokka","Tasmanian devil","Bottlebrush",
        "Wattle","Gum tree","Cane toad","Crocodile","Stingray","Frilled lizard",
        "Bilby","Numbat","Lorikeet","Jellyfish","Bull ant","Sugar glider",
        "Wallaby","Bandicoot","Bilby burrow","Pademelon","Potoroo","Antechinus",
        "Flying fox","Fruit bat","Microbat","Brushtail possum","Ringtail possum","Feathertail glider",
        "Squirrel glider","Rock wallaby","Tree kangaroo","Cassowary","Brolga","Jabiru",
        "Ibis","Pelican","Black swan","Wood duck","Willie wagtail","Blue wren",
        "Rosella","Galah","Corella","Sulphur crested cockatoo","Rainbow lorikeet","Honeyeater",
        "Currawong","Butcherbird","Whipbird","Bowerbird","Lyrebird tail","Emu chick",
        "Malleefowl","Wedge-tailed eagle","Sea eagle","Osprey","Barn owl","Tawny frogmouth",
        "Boobook","Carpet python","Brown snake","Tiger snake","Death adder","Taipan",
        "Blue tongue lizard","Thorny devil","Bearded dragon","Water dragon","Skink","Green tree frog",
        "Corroboree frog","Bull shark","Whale shark","Grey nurse","Dugong","Humpback",
        "Sea dragon","Clownfish","Coral polyp","Giant clam","Spinifex","Saltbush",
        "Paperbark","Ghost gum","Banksia","Waratah"],
      ACTION: [
        "Barbie","Surfing","Backyard cricket","Chuck a sickie","Bushwalk","Sausage sizzle",
        "Swooping","Shoey","Catching a wave","Snag flipping","Watching the footy","Doing a lap",
        "Having a squiz","Slip slop slap","Camping","Fishing off the jetty","Footy tipping","Chucking a uey",
        "Rocking up","Knocking off","Ducking out","Beach cricket","Bushfire watching","Riding a scooter",
        "Popping to the shops","Firing up the barbie","Cracking a tinnie","Hanging washing","Feeding the chooks","Mowing the lawn",
        "Throwing a boomerang","Flipping a snag","Shucking an oyster","Cracking a coldie","Sinking a tinnie","Lighting the barbie",
        "Turning the sausages","Buttering bread for a sanga","Squeezing sauce","Slapping on sunscreen","Rubbing in zinc","Jamming on a hat",
        "Swatting a fly","Slapping a mozzie","Shooing a magpie","Ducking a swoop","Waving away flies","Hanging out the washing",
        "Bringing in the washing","Pegging out a doona","Winding the Hills Hoist","Mowing the nature strip","Whipper snipping","Hosing the drive",
        "Watering the garden","Filling the pool","Skimming the pool","Chlorinating the pool","Bombing into the pool","Doing a dive bomb",
        "Belly flopping","Duck diving","Paddling out","Dropping in on a wave","Wiping out","Waxing a board",
        "Rinsing off sand","Shaking out a towel","Setting up a beach shelter","Digging a sandcastle","Burying someone in sand","Rock pooling",
        "Throwing a line in","Reeling in a fish","Netting a yabby","Riding a wave in","Baiting a hook","Gutting a fish",
        "Lighting a campfire","Boiling the billy","Toasting marshmallows","Rolling out a swag","Pitching a tent","Packing the ute",
        "Strapping down a load","Checking the tyres","Reversing a trailer","Doing a burnout","Bogging the car","Winching out of mud",
        "Opening a farm gate","Rounding up sheep","Shearing a sheep","Scattering chook feed","Collecting eggs","Milking a cow",
        "Cracking a whip","Riding a horse","Cutting firewood","Splitting logs"],
      PERSON: [
        "Steve Irwin","Ned Kelly","Cathy Freeman","Don Bradman","Kylie Minogue","John Howard",
        "Paul Hogan","The Wiggles","Hugh Jackman","Barry Humphries","Shane Warne","Ash Barty",
        "Ricky Ponting","Bindi Irwin","Nick Cave","Missy Higgins","Adam Goodes","Nicole Kidman",
        "Chris Hemsworth","Margot Robbie","Russell Crowe","Rebel Wilson","Bob Hawke","Julia Gillard",
        "John Farnham","Jimmy Barnes","Olivia Newton-John","Rod Laver","Greg Norman","Banjo Paterson",
        "Steve Waugh","Mark Waugh","Glenn McGrath","Adam Gilchrist","Michael Clarke","Pat Cummins",
        "Steve Smith","David Warner","Meg Lanning","Alyssa Healy","Belinda Clark","Ian Chappell",
        "Allan Border","Dennis Lillee","Merv Hughes","Mark Taylor","Bill Lawry","Richie Benaud",
        "Peter Brock","Dick Johnson","Craig Lowndes","Mark Webber","Daniel Ricciardo","Casey Stoner",
        "Mick Doohan","Mick Fanning","Stephanie Gilmore","Tyler Wright","Grant Hackett","Kieren Perkins",
        "Susie O'Neill","Dawn Fraser","Shane Gould","Libby Trickett","Sally Fitzgibbons","Anna Meares",
        "Sam Stosur","Pat Rafter","John Newcombe","Evonne Goolagong","Lauren Jackson","Andrew Gaze",
        "Buddy Franklin","Wayne Carey","Leigh Matthews","Ron Barassi","Johnathan Thurston","Cameron Smith",
        "Mal Meninga","Andrew Johns","Darren Lockyer","Tim Cahill","Harry Kewell","Mark Viduka",
        "Mark Schwarzer","Eddie Mabo","Fred Hollows","Howard Florey","Albert Namatjira","Henry Lawson",
        "Dorothea Mackellar","Sidney Nolan","Slim Dusty","Peter Allen","Cold Chisel","Midnight Oil",
        "Crowded House","Silverchair","Powderfinger","Tame Impala"],
      WORLD: [
        "Uluru","Bondi Beach","Sydney Opera House","Great Ocean Road","Gold Coast","Outback",
        "Blue Mountains","Melbourne laneway","Kakadu","Twelve Apostles","Harbour Bridge","Byron Bay",
        "Cairns","Perth","Adelaide","Darwin","Tasmania","Fraser Island",
        "Kangaroo Island","Snowy Mountains","Alice Springs","Margaret River","Whitsundays","Barossa Valley",
        "Port Douglas","MCG","Nullarbor","Daintree","Broome","Coober Pedy",
        "Brisbane","Canberra","Hobart","Newcastle","Wollongong","Geelong",
        "Ballarat","Bendigo","Toowoomba","Townsville","Rockhampton","Mackay",
        "Bundaberg","Noosa","Surfers Paradise","Coolangatta","Ballina","Coffs Harbour",
        "Port Macquarie","Newcastle beach","Central Coast","Manly","Cronulla","Palm Beach",
        "Bells Beach","Torquay","Lorne","Apollo Bay","Phillip Island","Mornington Peninsula",
        "Yarra Valley","Grampians","Wilsons Promontory","Great Dividing Range","Snowy River","Murray River",
        "Darling River","Lake Eyre","Simpson Desert","Kimberley","Bungle Bungles","Karijini",
        "Ningaloo Reef","Shark Bay","Rottnest Island","Margaret River caves","Esperance","Kalgoorlie",
        "Port Hedland","Katherine Gorge","Litchfield","Tiwi Islands","Arnhem Land","Cape York",
        "Torres Strait","Whitehaven Beach","Magnetic Island","Lady Elliot Island","Lord Howe Island","Cradle Mountain",
        "Wineglass Bay","Port Arthur","Salamanca","Freycinet","Bruny Island","Flinders Ranges",
        "Barossa","Coonawarra","Fleurieu Peninsula","Kangaroo Valley"],
      RANDOM: [
        "Vegemite","Fairy bread","Lamington","Tim Tam","Servo pie","Milk bar",
        "Sunnies","Arvo","Servo","Bottle-o","Chook","Ute muster",
        "Bogan","Cossie","Doona","Op shop","Ripper","Fair dinkum",
        "She'll be right","Yeah nah","Cane toad race","Meat raffle","Snag sandwich","Sausage in bread",
        "Two-up","Melbourne Cup","Boxing Day Test","Schoolies","Straya Day","Footy finals",
        "Barbie sauce","Dead horse","Cuppa","Cold one","Coldie","Middy",
        "Schooner","Pot of beer","Slab","Six pack","Bottle shop","Drive through bottle-o",
        "Servo coffee","Servo dog","Sausage roll","Party pie","Potato scallop","Dim sim",
        "Battered sav","Hot chips","Chicken salt","Gravy roll","Iced coffee","Milo",
        "Weet-Bix","Golden Gaytime","Bubble o Bill","Paddle Pop","Splice","Icy pole",
        "Musk stick","Freddo","Caramello Koala","Minties","Jaffas","Redskin",
        "Wagon Wheel","Iced VoVo","Monte Carlo","Scotch Finger","Anzac biscuit","Pavlova",
        "Damper","Chiko","Dagwood dog","Show bag","Sideshow alley","Country show",
        "B&S ball","Bush dance","Backyard cricket rules","Tip and run","Six and out","One hand one bounce",
        "Nicko","Sanga","Barbie chat","Smoko","Knock off time","Sickie",
        "Long weekend","Public holiday","Australia Day lamb ad","Boxing Day sales","Anzac dawn service","Melbourne Cup sweep",
        "Footy tipping comp","Meat tray","Chook raffle","Bogan bingo"],
      DRAW: [
        "A kangaroo","A meat pie","A Hills Hoist","A surfboard","A boomerang","An esky",
        "A koala in a tree","A pair of thongs","A ute","A magpie swooping","The Opera House","Ayers Rock at sunset",
        "A lamington","A Tim Tam","A cricket bat","A wombat","A platypus","A bin chicken",
        "A barbie","A swag","The Harbour Bridge","A kookaburra","A Vegemite jar","A stubby holder",
        "A cane toad","A shark warning sign","A beach umbrella","A campfire","A cattle dog","A road train",
        "A goanna","A frilled lizard","A dingo","A bilby","A quokka","A cassowary",
        "A pelican","A galah","A cockatoo","A rosella","An emu","A crocodile",
        "A blue tongue lizard","A huntsman spider","A redback","A jellyfish","A stingray","A dugong",
        "A whale tail","A shark fin","A gum leaf","A wattle branch","A bottlebrush","A banksia",
        "A waratah","A ghost gum","A billabong","A waterhole","A red dirt road","A cattle grid",
        "A farm gate","A windmill on a farm","A water tank","A shearing shed","A hay bale","A tractor",
        "A quad bike","A four wheel drive","A boat on a trailer","A tinnie","A jetty","A stock crate",
        "A fishing rod","A crab pot","A yabby","A prawn","An oyster","A meat tray",
        "A sausage on bread","A pie with sauce","A Chiko roll","A dagwood dog","A pav with cream","A lamington on a plate",
        "An Anzac biscuit","A Vegemite sandwich","A Milo tin","A Weet-Bix box","A thermos","A camp oven",
        "A billy on a fire","A swag rolled up","A tent","A beach shelter","A boogie board","A zinc stripe",
        "A wide brim hat","A pair of work boots","A high vis vest","A Southern Cross"],
  }, {
      OBJECT: [],
      NATURE: [],
      RANDOM: [],
      ACTION: [],
      PERSON: [],
      WORLD: [],
      DRAW: [],
  }),

  deck("Kids Zone", "family friendly", "balloon",
    "Simple, friendly words the whole table can shout out. Nothing anyone needs explaining.", {
      OBJECT: [
        "Teddy bear","Skateboard","Balloon","Backpack","Crayon","Bicycle",
        "Kite","Lunchbox","Torch","Skipping rope","Bucket","Spade",
        "Football","Puzzle","Marble","Yo-yo","Whistle","Drum",
        "Scooter","Sandcastle","Toy car","Building block","Water pistol","Bubble wand",
        "Paint brush","Sticker","Board game","Piggy bank","Umbrella","Kaleidoscope",
        "Wagon","Tricycle","Trampoline","Swing","Slide","Seesaw",
        "Sandpit bucket","Beach ball","Frisbee","Hula hoop","Pogo stick","Space hopper",
        "Rocking horse","Doll","Doll house","Action figure","Toy train","Train track",
        "Race track","Remote control car","Kite string","Paper plane","Paper boat","Origami crane",
        "Colouring book","Sticker sheet","Glue stick","Safety scissors","Glitter pot","Play dough",
        "Finger paint","Chalk","Blackboard","Whiteboard","Pencil sharpener","Rubber",
        "Exercise book","Reading book","Bookmark","Night light","Lamp","Dressing gown",
        "Slippers","Wellington boots","Raincoat","Beanie","Mittens","Scarf",
        "Swimming goggles","Armbands","Snorkel","Flippers","Surfboard","Boogie board",
        "Bucket and spade","Fishing net","Magnifying glass","Binoculars","Compass","Satchel",
        "Water bottle","Lunch box","Drink bottle","Sandwich box","Apple","Banana",
        "Juice box","Straw","Spoon","Bowl"],
      NATURE: [
        "Rainbow","Butterfly","Puppy","Kitten","Snowflake","Sunflower",
        "Ladybird","Frog","Rabbit","Duckling","Tadpole","Caterpillar",
        "Acorn","Seashell","Starfish","Penguin","Dolphin","Elephant",
        "Giraffe","Monkey","Bumblebee","Snail","Owl","Hedgehog",
        "Squirrel","Turtle","Panda","Daisy","Pine cone","Puddle",
        "Fox cub","Wolf pup","Pony","Lamb","Calf","Piglet",
        "Chick","Cygnet","Gosling","Bunny","Hamster","Guinea pig",
        "Goldfish","Parrot","Budgie","Canary","Peacock","Flamingo",
        "Ostrich","Emu","Swan","Pelican","Seagull","Crab",
        "Lobster","Jellyfish","Seahorse","Octopus","Whale","Shark",
        "Clownfish","Angelfish","Lizard","Gecko","Chameleon","Tortoise",
        "Crocodile","Hippo","Rhino","Zebra","Lion","Tiger",
        "Cheetah","Leopard","Bear","Wolf","Fox","Deer",
        "Moose","Koala","Kangaroo","Sloth","Camel","Llama",
        "Alpaca","Donkey","Goat","Sheep","Cow","Horse",
        "Rain","Snow","Wind","Sunshine","Cloud","Thunder",
        "Lightning","Rock","Shell","Feather"],
      // Every one of these is something you can stand up and DO. "Building a
      // fort" was a scene, not an action, and died on its feet.
      ACTION: [
        "Jumping","Skipping","Splashing","Giggling","Tiptoeing","Cartwheeling",
        "Blowing bubbles","Hiding","Colouring in","Sneaking","Piggyback ride","Somersault",
        "Clapping","Whistling","Tickling","Waving","Swinging","Sliding",
        "Hopping","Spinning","Sneezing","Yawning","Marching","Dancing",
        "Running","Rolling downhill","Blowing out a candle","Popping a balloon","Skimming a stone","Climbing",
        "Skipping rope","Hopscotching","Somersaulting","Cartwheeling fast","Doing a handstand","Doing a forward roll",
        "Star jumping","Bunny hopping","Frog jumping","Crab walking","Bear crawling","Tiptoeing quietly",
        "Stomping","Marching in line","Galloping","Skating","Cycling","Scootering",
        "Swimming","Floating","Diving","Splashing about","Paddling","Kicking a ball",
        "Throwing a ball","Catching a ball","Bouncing a ball","Rolling a ball","Batting","Bowling",
        "Serving","Dribbling","Juggling","Balancing","Wobbling","Falling over",
        "Getting back up","Stretching","Touching your toes","Reaching up high","Crouching down","Curling up small",
        "Standing tall","Sitting cross-legged","Kneeling","Lying down","Rolling over","Waking up",
        "Rubbing your eyes","Brushing your teeth","Washing your hands","Combing your hair","Getting dressed","Tying shoelaces",
        "Zipping a coat","Buttoning a shirt","Packing a bag","Waving goodbye","Blowing a kiss","Shaking hands",
        "Nodding","Shaking your head","Shrugging","Pointing","Counting on fingers","Whispering",
        "Shouting","Laughing","Crying","Skipping along"],
      PERSON: [
        "Taylor Swift","Cristiano Ronaldo","Lionel Messi","Steve Irwin","Bindi Irwin","David Attenborough",
        "Ed Sheeran","Beyoncé","Dwayne Johnson","Serena Williams","Usain Bolt","Michael Jordan",
        "Katy Perry","Justin Bieber","Ariana Grande","Harry Styles","Adele","Bruno Mars",
        "Billie Eilish","Dua Lipa","MrBeast","Emma Watson","Daniel Radcliffe","Tom Holland",
        "Zendaya","Simone Biles","Neil Armstrong","Albert Einstein","Roald Dahl","Walt Disney",
        "Cristiano Ronaldo Jr","Sam Kerr","Ellyse Perry","Ash Barty","Cathy Freeman","Emma McKeon",
        "Dylan Alcott","Patty Mills","LeBron James","Stephen Curry","Neymar","Kylian Mbappe",
        "Erling Haaland","Mo Salah","Harry Kane","Megan Rapinoe","Alex Morgan","Naomi Osaka",
        "Coco Gauff","Rafael Nadal","Roger Federer","Novak Djokovic","Tiger Woods","Lewis Hamilton",
        "Daniel Ricciardo","Valentino Rossi","Michael Phelps","Ian Thorpe","Ariarne Titmus","Kaylee McKeown",
        "Nick Kyrgios","Buddy Franklin","Johnathan Thurston","Selena Gomez","Miley Cyrus","Shawn Mendes",
        "Camila Cabello","Olivia Rodrigo","Lizzo","Rihanna","Justin Timberlake","Pink",
        "Sia","Delta Goodrem","Guy Sebastian","Keith Urban","Hugh Jackman","Chris Hemsworth",
        "Margot Robbie","Rebel Wilson","Jackie Chan","Will Smith","Tom Cruise","Johnny Depp",
        "Jim Carrey","Eddie Murphy","Robin Williams","Whoopi Goldberg","Oprah Winfrey","Ellen DeGeneres",
        "Bear Grylls","Jane Goodall","Marie Curie","Isaac Newton","Galileo","Amelia Earhart",
        "Nelson Mandela","Anne Frank","Beatrix Potter","Dr Seuss"],
      WORLD: [
        "Playground","Zoo","Beach","Farm","Library","Treehouse",
        "Circus","Museum","Swimming pool","Campsite","Aquarium","Toy shop",
        "Bakery","Park","Ice rink","Castle","Lighthouse","Bus stop",
        "Fairground","Petting zoo","Forest","Cave","Island","Desert",
        "Mountain","Rocket ship","Igloo","Windmill","Bridge","Waterfall",
        "School","Classroom","Playground slide","Sports field","Gymnasium","Swimming lesson",
        "Dance studio","Music room","Art room","Science lab","Cafeteria","School bus",
        "Corner shop","Supermarket","Post office","Fire station","Police station","Hospital",
        "Dentist","Doctor's surgery","Vet clinic","Pet shop","Book shop","Toy aisle",
        "Sweet shop","Ice cream van","Playcentre","Trampoline park","Skate park","Bike track",
        "Bowling alley","Cinema","Theatre","Puppet show","Magic show","Fun park",
        "Ferris wheel","Roller coaster","Merry-go-round","Bumper cars","Water slide","Wave pool",
        "Splash pad","Camping ground","Tent","Cabin","Caravan","Farm shed",
        "Barn","Stable","Chicken coop","Orchard","Berry farm","Pumpkin patch",
        "Corn maze","Lighthouse hill","Rock pool","Sand dune","Jetty","Pier",
        "Harbour","Ferry","Train station","Airport","Space station","Planetarium",
        "Dinosaur museum","Botanic garden","Butterfly house","Petting farm"],
      RANDOM: [
        "Bubble","Sprinkles","Glitter","Tickle","Wiggle","Hiccup",
        "Freckle","Pyjamas","Bedtime story","Tooth fairy","Birthday cake","Party hat",
        "Balloon animal","Face paint","Piñata","Lemonade stand","Sleepover","Hopscotch",
        "Musical chairs","Show and tell","Silly face","Bear hug","Secret handshake","Snow day",
        "Puddle jumping","Nap time","Playdate","Dress-up box","Sandpit","Wobbly tooth",
        "Balloon pop","Party bag","Party popper","Candle","Wish","Secret",
        "Surprise","Giggle","Whisper","Shout","Tickle fight","Pillow fight",
        "Water fight","Snowball fight","Cuddle","High five","Fist bump","Thumbs up",
        "Wink","Silly walk","Funny voice","Knock knock joke","Riddle","Rhyme",
        "Song","Lullaby","Nursery rhyme","Alphabet","Counting","Colours",
        "Shapes","Numbers","Puzzle piece","Jigsaw","Dot to dot","Maze",
        "Spot the difference","I spy","Twenty questions","Simon says","Duck duck goose","Musical statues",
        "Pass the parcel","Pin the tail","Egg and spoon","Sack race","Three-legged race","Tug of war",
        "Skipping game","Clapping game","Hand shadow","Cartwheel","Handstand","Forward roll",
        "Bunny hop","Star jump","Frog jump","Crab walk","Bear crawl","Wobbly tooth fairy",
        "Loose tooth","Growth chart","Report card","Gold star","Sticker chart","Show bag",
        "Lucky dip","Fancy dress","Face paint tiger","Balloon sword"],
      DRAW: [
        "A smiling sun","A rocket","A cat","A house","A rainbow","A dinosaur",
        "A robot","An ice cream","A flower","A boat","A butterfly","A snowman",
        "A tree","A fish","A birthday cake","A hot air balloon","A castle","A dog",
        "A star","A car","A ladybird","A kite","A frog","A crown",
        "A pirate ship","An umbrella","A snail","A duck","A cupcake","A teddy bear",
        "A smiling face","A stick figure","A family","A baby","A crown on a head","A wizard hat",
        "A witch hat","A pirate hat","A cowboy hat","A police car","A fire engine","An ambulance",
        "A tractor","A digger","A truck","A bus","A train","A plane",
        "A helicopter","A submarine","A sailing boat","A canoe","A bicycle","A scooter",
        "A skateboard","A pair of roller skates","A ball","A bat","A goal","A trophy",
        "A medal","A drum","A guitar","A trumpet","A piano","A microphone",
        "A book","A pencil","A paintbrush","A palette","A pair of scissors","A glue stick",
        "A backpack","A lunchbox","An apple","A banana","A pear","A carrot",
        "A slice of pizza","A hot dog","A doughnut","A lollipop","A candy cane","A gingerbread man",
        "A snow globe","A present","A bow","A balloon","A party hat","A candle on a cake",
        "A moon","A cloud","A raindrop","A snowflake","A lightning bolt","A mountain",
        "A river","A bridge over water","A treehouse","A tent"],
  }, {
      OBJECT: [],
      NATURE: [],
      RANDOM: [],
      ACTION: [],
      PERSON: [],
      WORLD: [],
      DRAW: [],
  }),

  deck("Movies & TV", "adults (clean)", "clapper",
    "Blockbusters, cult classics and the shows people still quote at each other.", {
      OBJECT: [
        "Popcorn bucket","Film reel","Clapperboard","Remote control","3D glasses","Cinema ticket",
        "Red carpet","Oscar statue","Boom mic","Director's chair","Green screen","Movie poster",
        "DVD box set","Projector","Ticket stub","Velvet rope","Usher torch","Slushie cup",
        "Screen curtain","Camera dolly","Storyboard","Prop sword","Fake blood","Wind machine",
        "Stunt harness","Teleprompter","Subtitle bar","Rating sticker","Cinema seat","Concession stand"],
      NATURE: [
        "Jurassic jungle","Shark fin","King Kong's island","Twister","Desert planet","Volcano lair",
        "Haunted forest","Snowy tundra","Deep space","Ocean trench","Swamp","Savannah",
        "Jungle vine","Cliff edge","Torrential rain","Blood red sunset","Meteor strike","Iceberg",
        "Sand storm","Canyon","Alien landscape","Coral lagoon","Piranha river","Bamboo forest",
        "Moon surface","Thunder and lightning","Wolf howl","Giant eagle","Creeping fog","Cave system"],
      ACTION: [
        "Binge watching","Skipping the intro","Rewinding a scene","Pausing to snack","Quoting a film","Booing a villain",
        "Cheering the hero","Crying at the end","Queuing for tickets","Auditioning","Method acting","Improvising",
        "Lip syncing","Screen testing","Stunt doubling","Directing","Editing","Voice acting",
        "Spoiling the ending","Live tweeting","Arguing about the ending","Walking the red carpet","Taking a bow","Applauding",
        "Sneaking snacks in","Reading subtitles","Filming a montage","Rolling the credits","Rating a film","Sitting through the credits"],
      PERSON: [
        "Tom Hanks","Meryl Streep","Leonardo DiCaprio","Denzel Washington","Julia Roberts","Steven Spielberg",
        "Quentin Tarantino","Morgan Freeman","Robert De Niro","Al Pacino","Samuel L Jackson","Scarlett Johansson",
        "Brad Pitt","Angelina Jolie","Will Smith","Jennifer Aniston","Robin Williams","Jim Carrey",
        "Eddie Murphy","Arnold Schwarzenegger","Keanu Reeves","Cate Blanchett","Oprah Winfrey","Ricky Gervais",
        "Steve Carell","Bryan Cranston","Tom Cruise","Harrison Ford","Anthony Hopkins","Charlie Chaplin"],
      WORLD: [
        "Hogwarts","Middle-earth","Gotham City","Jurassic Park","The Shire","Wakanda",
        "Hill Valley","Springfield","Westeros","Pandora","Narnia","Neverland",
        "Oz","Death Star","Bikini Bottom","Mordor","The Matrix","Tatooine",
        "Hollywood Boulevard","Sunnydale","Bedrock","Duckburg","Metropolis","Atlantis",
        "Isla Nublar","Arrakis","The Upside Down","Stars Hollow","Amity Island","Zootopia"],
      RANDOM: [
        "Sequel","Reboot","Cameo","Blooper","Cliff-hanger","Spin-off",
        "Binge","Trailer","Post-credits scene","Box office","Franchise","Fan theory",
        "Season finale","Pilot episode","Streaming","Subtitles","Dubbing","Soundtrack",
        "Screenplay","Casting","Prequel","Anti-hero","Sidekick","Nemesis",
        "Plot armour","Catchphrase","Laugh track","Blockbuster","Award season","Cult classic"],
      DRAW: [
        "A film clapperboard","Popcorn","A cinema screen","A movie camera","A red carpet","An Oscar",
        "A 3D pair of glasses","A director's chair","A ticket stub","A film reel","A lightsaber","A wizard hat",
        "A shark fin","A DeLorean","A dinosaur","A superhero cape","A crown","A spaceship",
        "A cowboy hat","A ring","A haunted house","A pirate flag","A robot","A detective magnifier",
        "A microphone","A boom mic","A projector","A drive-in screen","A movie poster","A theatre curtain"],
  }),

  deck("Sports Legends", "teens", "trophy",
    "Players, moments and gear from across the codes. You don't have to be a fanatic to get these.", {
      OBJECT: [
        "Football","Cricket bat","Tennis racquet","Boxing glove","Surfboard","Golf club",
        "Hockey stick","Basketball","Whistle","Stopwatch","Goal post","Scoreboard",
        "Trophy","Medal","Shin pad","Mouthguard","Swim goggles","Running spikes",
        "Baseball mitt","Helmet","Skipping rope","Weight bench","Yellow card","Starting block",
        "Ski poles","Netball bib","Water bottle","Bike helmet","Dartboard","Bowling ball"],
      NATURE: [
        "Mountain","Ocean","Rapids","Snowfield","Sand dune","Gale",
        "Mud","Blazing sun","Reef","Alpine forest","Desert","Frozen lake",
        "Forest","Heatwave","Fog","Ocean current","Snowstorm","Hailstorm",
        "Sea spray","Cliff","Waterfall","Glacier","Canyon","Thunderstorm",
        "Lightning","Blizzard","Tide","Headland","Rockface","Whitewater"],
      ACTION: [
        "Slam dunk","Home run","Hat-trick","Penalty kick","Bowled out","Try scored",
        "Knockout","Photo finish","Sprint","Tackle","Marathon","Dive",
        "Backflip","Volley","Free throw","Lay-up","Sledging","Streaking",
        "Warming up","Cooling down","Substitution","Time out","Half time","Overtime",
        "Extra time","Lap of honour","Podium finish","Post-match interview","Coin toss","Full time whistle"],
      PERSON: [
        "Michael Jordan","Serena Williams","Usain Bolt","Muhammad Ali","Pelé","Cathy Freeman",
        "Shane Warne","Tiger Woods","Roger Federer","Lionel Messi","Cristiano Ronaldo","Simone Biles",
        "Ash Barty","Don Bradman","Ian Thorpe","Layne Beachley","Sally Pearson","Adam Goodes",
        "Rafael Nadal","Lewis Hamilton","Diego Maradona","Sam Kerr","Ellyse Perry","Michael Phelps",
        "LeBron James","Ayrton Senna","Dylan Alcott","Emma McKeon","Babe Ruth","Martina Navratilova"],
      WORLD: [
        "Olympic stadium","Camp Nou","Wimbledon","MCG","Alpe d'Huez","Yankee Stadium",
        "Lord's","Suncorp Stadium","Flemington","Eden Park","Wembley","Old Trafford",
        "Maracanã","Madison Square Garden","Augusta","Monaco circuit","Bondi","Everest base camp",
        "Kokoda Track","Bells Beach","Rio","Tokyo","Paris","Barcelona",
        "Sydney","Athens","Beijing","Los Angeles","Brisbane","Manchester"],
      RANDOM: [
        "Offside","Red card","Sudden death","Underdog","Rivalry","Team jersey",
        "Half-time orange","Fantasy league","Transfer window","Draft pick","Bench warmer","Season ticket",
        "Sportsmanship","Trash talk","Comeback","Winning streak","Losing streak","Hall of fame",
        "Record breaker","Dark horse","Home advantage","Away game","Derby","Testimonial",
        "Warm-up lap","Drug test","Injury time","Man of the match","Wooden spoon","Grand slam"],
      DRAW: [
        "A football","A trophy","A medal","A whistle","A goal post","A cricket bat",
        "A tennis racquet","A boxing glove","A surfboard","A basketball hoop","A running shoe","A stopwatch",
        "A scoreboard","A podium","A referee","A helmet","A bicycle","A swimming pool",
        "A dartboard","A golf flag","A red card","A skateboard","A ski slope","A finish line",
        "A weight","A jersey","A hockey stick","A baseball mitt","A pair of goggles","A racing car"],
  }),

  deck("Around the House", "family friendly", "house",
    "Everyday things hiding in plain sight, which turns out to be far harder to describe than it sounds.", {
      OBJECT: [
        "Kettle","Toaster","Doorbell","Coat hanger","Ironing board","Vacuum cleaner",
        "Mop","Laundry basket","Bin lid","Tea towel","Doormat","Light switch",
        "Curtain rail","Fridge magnet","Bread bin","Chopping board","Colander","Whisk",
        "Peeler","Corkscrew","Torch","Extension cord","Smoke alarm","Sewing kit",
        "Toolbox","Spirit level","Watering can","Step ladder","Clothes peg","Dustpan",
        "Microwave","Oven","Grill","Rangehood","Dishwasher","Sink plug",
        "Draining rack","Scourer","Sponge","Dish brush","Rubber gloves","Bin bag",
        "Bin liner","Pedal bin","Recycling crate","Dustpan brush","Broom head","Feather duster",
        "Microfibre cloth","Window squeegee","Bucket","Mop head","Steam mop","Carpet shampooer",
        "Lint roller","Clothes brush","Shoe horn","Shoe polish","Boot rack","Umbrella stand",
        "Coat rack","Key hook","Doorstop","Draught excluder","Door chain","Deadlock",
        "Spy hole","Doorbell chime","Intercom","Alarm panel","Motion sensor","Security camera",
        "Floodlight","Porch light","Lamp shade","Bedside lamp","Reading light","Dimmer switch",
        "Power point","Power board","Surge protector","Extension lead","Cable tie","Cord clip",
        "Battery pack","Torch beam","Head torch","Candle holder","Matchbox","Lighter",
        "Fire blanket","Fire extinguisher","Smoke detector","Carbon monoxide alarm","First aid kit","Plaster",
        "Bandage","Thermometer","Hot water bottle","Heat pack","Electric blanket","Heater",
        "Fan heater","Pedestal fan","Air conditioner","Dehumidifier","Air purifier","Humidifier",
        "Radiator","Thermostat","Draught snake","Curtain","Blind","Venetian blind",
        "Roller blind","Curtain hook","Curtain tieback","Cushion","Cushion cover","Throw rug",
        "Blanket","Doona cover","Pillow case","Mattress protector","Fitted sheet","Flat sheet",
        "Bed frame","Bed head","Bedside table","Chest of drawers","Wardrobe","Coat hanger rail",
        "Shoe box","Storage tub","Vacuum bag","Suitcase","Laundry hamper","Peg bag",
        "Washing powder","Fabric softener","Stain remover","Iron","Ironing spray","Clothes airer",
        "Drying rack","Tumble dryer","Lint trap","Sewing machine","Needle and thread","Pin cushion",
        "Tape measure","Spirit bubble","Stud finder","Drill","Drill bit","Screwdriver set",
        "Allen key","Spanner","Adjustable wrench","Pliers","Wire cutter","Hacksaw",
        "Hand saw","Chisel","Sandpaper","Paint tin","Paint brush","Paint tray",
        "Drop sheet","Masking tape","Filler","Putty knife","Caulking gun","Silicone tube",
        "Grout","Tile spacer","Trowel","Spirit level bubble","Plumb line","Nail",
        "Screw","Wall plug","Picture hook","Command strip","Duct tape","Electrical tape",
        "Glue gun","Super glue","WD-40","Oil can","Grease gun","Watering can rose",
        "Secateurs","Hedge trimmer","Leaf blower","Rake","Garden fork","Spade",
        "Trowel set","Kneeling pad"],
      NATURE: [
        "Houseplant","Lawn","Weeds","Compost heap","Veggie patch","Spider web",
        "Mould","Dust","Fallen leaves","Moth","Bird nest","Hedge",
        "Rose bush","Ant","Spider","Snail","Ladybird","Earthworm",
        "Possum","Mouse","Cockroach","Fern","Ivy","Lavender",
        "Tomato plant","Dandelion","Butterfly","Beehive","Frost","Puddle",
        "Ant trail","Aphid","Slug","Woodlouse","Silverfish","Millipede",
        "Centipede","Beetle","Ladybug","Cricket","Grasshopper","Cicada",
        "Wasp","Hornet","Bumblebee","Honeybee","Hoverfly","Blowfly",
        "Mosquito","Midge","Gnat","Dragonfly","Damselfly","Butterfly wing",
        "Caterpillar","Cocoon","Chrysalis","Spider egg","Daddy long legs","Huntsman",
        "Wolf spider","Jumping spider","Web strand","Sparrow","Starling","Blackbird",
        "Robin","Wren","Finch","Swallow","Swift","Pigeon",
        "Dove","Crow","Magpie nest","Kookaburra call","Owl pellet","Bat",
        "Hedgehog","Mole","Vole","Field mouse","Rat","Squirrel",
        "Rabbit hole","Fox","Possum in the roof","Cat on a fence","Dog next door","Chicken",
        "Rooster","Duck pond","Frog spawn","Tadpole","Newt","Lizard",
        "Snake skin","Snail shell","Earwig","Worm cast","Moss","Lichen",
        "Algae","Fungus","Toadstool","Mushroom ring","Fern frond","Ivy vine",
        "Creeper","Climbing rose","Wisteria","Honeysuckle","Jasmine","Lavender bush",
        "Rosemary","Thyme","Basil","Mint","Parsley","Chives",
        "Sage","Oregano","Dill","Coriander","Tomato plant vine","Chilli bush",
        "Capsicum plant","Zucchini flower","Pumpkin vine","Bean pole","Pea shoot","Lettuce head",
        "Spinach leaf","Silverbeet","Rhubarb","Strawberry runner","Raspberry cane","Blueberry bush",
        "Grape vine","Lemon tree","Lime tree","Orange tree","Apple blossom","Pear tree",
        "Plum tree","Fig leaf","Olive branch","Avocado seed","Banana leaf","Palm frond",
        "Bamboo cane","Hedge clipping","Grass clipping","Turf","Lawn seed","Weed root",
        "Dandelion clock","Daisy chain","Clover","Buttercup","Bluebell","Daffodil",
        "Tulip","Crocus","Snowdrop","Hyacinth","Geranium","Petunia",
        "Pansy","Marigold","Sunflower head","Hydrangea","Camellia","Azalea",
        "Rhododendron","Magnolia","Gardenia","Frangipani","Bougainvillea","Agapanthus",
        "Succulent","Cactus","Aloe","Spider plant","Peace lily","Fiddle leaf fig",
        "Monstera","Pothos","Bonsai tree","Terrarium","Window box","Hanging basket",
        "Compost worm","Mulch","Topsoil","Potting mix","Rainwater","Dew on grass",
        "Morning frost","Hail on the roof"],
      ACTION: [
        "Vacuuming","Washing up","Hanging washing","Mowing the lawn","Taking the bins out","Making the bed",
        "Folding laundry","Dusting","Changing a bulb","Locking up","Defrosting the freezer","Unblocking the sink",
        "Watering plants","Sweeping","Ironing","Cooking dinner","Setting the table","Doing the dishes",
        "Painting a wall","Hammering a nail","Hanging a picture","Assembling flat-pack","Reading the meter","Sorting recycling",
        "Cleaning windows","Wiping benches","Feeding the pet","Scrubbing the shower","Changing sheets","Putting up shelves",
        "Sweeping the floor","Mopping","Scrubbing a pan","Rinsing plates","Stacking the dishwasher","Emptying the dishwasher",
        "Drying up","Putting away dishes","Wiping the bench","Wiping a spill","Clearing the table","Laying the table",
        "Serving dinner","Boiling the kettle","Making tea","Pouring milk","Buttering toast","Packing lunches",
        "Unpacking shopping","Stacking the fridge","Checking a use-by date","Throwing out leftovers","Taking out recycling","Tying a bin bag",
        "Wheeling out the bin","Bringing in the bin","Sorting laundry","Loading the washing","Hanging out washing","Pegging a shirt",
        "Bringing in washing","Folding towels","Pairing socks","Ironing a shirt","Steaming a dress","Sewing a button",
        "Mending a hem","Polishing shoes","Dusting a shelf","Wiping a mirror","Vacuuming stairs","Beating a rug",
        "Shaking a doormat","Fluffing a cushion","Making a bed","Plumping pillows","Airing a room","Opening curtains",
        "Drawing curtains","Lowering a blind","Turning on a lamp","Changing a light bulb","Resetting a breaker","Replacing a battery",
        "Testing a smoke alarm","Setting a thermostat","Bleeding a radiator","Lighting a fire","Stacking firewood","Sweeping a hearth",
        "Unblocking a sink","Plunging a drain","Fixing a tap washer","Tightening a screw","Oiling a hinge","Levelling a shelf",
        "Measuring a wall","Marking a drill hole","Drilling a hole","Sanding a surface","Priming a wall","Rolling paint",
        "Cutting in with a brush","Taping an edge","Peeling masking tape","Filling a crack","Smoothing filler","Grouting tiles",
        "Sealing a bath","Assembling flat pack","Reading instructions","Losing a screw","Tightening a bolt","Mowing stripes",
        "Edging a lawn","Raking leaves","Bagging clippings","Weeding a bed","Digging a hole","Planting a seedling",
        "Potting a plant","Repotting","Pruning a bush","Deadheading roses","Trimming a hedge","Watering pots",
        "Coiling a hose","Turning compost","Spreading mulch","Sowing seed","Staking a plant","Picking tomatoes",
        "Harvesting herbs","Feeding a pet","Filling a water bowl","Walking the dog","Brushing a cat","Cleaning a litter tray",
        "Refilling a bird feeder","Washing the car","Vacuuming the car","Checking tyre pressure","Topping up the washer fluid","Checking the doors",
        "Setting the alarm","Answering the door","Signing for a parcel","Putting up a shelf","Boxing up donations","Dropping at the op shop",
        "Labelling a box","Wrapping a glass","Taping a box","Loading a car","Carrying a couch","Shuffling furniture",
        "Rolling a rug","Sweeping a garage","Hosing a driveway","Cleaning gutters","Climbing a ladder","Holding a ladder",
        "Reaching a high shelf","Bending to a low cupboard","Kneeling to clean","Stretching to dust","Squeezing behind the fridge","Moving the sofa to hoover",
        "Finding a coin under a cushion","Untangling cables","Winding a cord","Charging a phone","Changing a filter","Descaling a kettle",
        "Defrosting a freezer","Wiping down a fridge","Cleaning an oven","Scraping a grill","Emptying a vacuum","Replacing a vacuum bag",
        "Cleaning a shower screen","Scrubbing a bath","Bleaching a toilet","Restocking loo roll","Hanging a fresh towel","Refilling soap",
        "Watering a house plant","Wiping leaves of a plant","Turning a plant to the light","Opening a stuck jar","Reaching a spider with a glass","Putting a spider outside",
        "Swatting a fly","Setting a mousetrap","Sealing a gap"],
      // Broad household names rather than renovation specialists: the faces that
      // are literally in your living room every night, which keeps a thread to
      // the deck without needing 30 famous plumbers.
      PERSON: [
        "Martha Stewart","Marie Kondo","Scott Cam","Shaynna Blaze","Don Burke","Costa Georgiadis",
        "Johanna Griggs","Dr Harry Cooper","Karl Stefanovic","Lisa Wilkinson","Eddie McGuire","Rove McManus",
        "Hamish Blake","Andy Lee","Carrie Bickmore","Waleed Aly","Shaun Micallef","Magda Szubanski",
        "Bert Newton","Daryl Somers","Molly Meldrum","Ray Martin","Tracy Grimshaw","David Attenborough",
        "Oprah Winfrey","Bear Grylls","Gordon Ramsay","Jamie Oliver","Ellen DeGeneres","Graham Norton",
        "Barack Obama","Michelle Obama","Nelson Mandela","Winston Churchill","Queen Elizabeth","King Charles",
        "Prince William","Princess Diana","David Beckham","Victoria Beckham","Elton John","Paul McCartney",
        "Ed Sheeran","Adele","Dolly Parton","Willie Nelson","Bruce Springsteen","Bob Dylan",
        "Stevie Wonder","Tina Turner","Whitney Houston","Aretha Franklin","Freddie Mercury","David Bowie",
        "Prince","Michael Jackson","Madonna","Beyonce","Rihanna","Taylor Swift",
        "Billie Eilish","Dua Lipa","Harry Styles","Justin Timberlake","Bruno Mars","Usher",
        "Alicia Keys","John Legend","Lady Gaga","Katy Perry","Pink","Sia",
        "Kylie Minogue","Olivia Newton-John","John Farnham","Jimmy Barnes","Nick Cave","Keith Urban",
        "Guy Sebastian","Delta Goodrem","Hugh Jackman","Nicole Kidman","Cate Blanchett","Russell Crowe",
        "Chris Hemsworth","Margot Robbie","Rebel Wilson","Eric Bana","Geoffrey Rush","Toni Collette",
        "Isla Fisher","Rose Byrne","Sam Neill","Tom Hanks","Meryl Streep","Denzel Washington",
        "Morgan Freeman","Robert De Niro","Al Pacino","Julia Roberts","Sandra Bullock","Jennifer Aniston",
        "Reese Witherspoon","Emma Stone","Anne Hathaway","Kate Winslet","Judi Dench","Helen Mirren",
        "Maggie Smith","Ian McKellen","Patrick Stewart","Anthony Hopkins","Michael Caine","Sean Connery",
        "Pierce Brosnan","Liam Neeson","Colin Firth","Hugh Grant","Emma Thompson","Rowan Atkinson",
        "Ricky Gervais","Stephen Fry","Michael Palin","John Cleese","Billy Connolly","Peter Kay",
        "Miriam Margolyes","Dawn French","Jennifer Saunders","Jo Brand","Sue Perkins","Mary Berry",
        "Prue Leith","Paul Hollywood","Nigella Lawson","Rick Stein","Nigel Slater","Delia Smith",
        "Ainsley Harriott","Curtis Stone","Matt Preston","Maggie Beer","Adam Liaw","Poh Ling Yeow",
        "Manu Feildel","Melissa Leong","Andy Allen","Jock Zonfrillo","Julie Goodwin","Marion Grasby",
        "Donna Hay","Kylie Kwong","Matt Moran","Neil Perry","Colin Fassnidge","Shannon Bennett",
        "Jane Goodall","Steve Irwin","Bindi Irwin","Robert Irwin","Peter Cundall","Graham Ross",
        "Jamie Durie","Neale Whitaker","Darren Palmer","Barry Du Bois","Andrew Winter","Kevin McCloud",
        "Laurence Llewelyn-Bowen","Kirstie Allsopp","Phil Spencer","Sarah Beeny","Ty Pennington","Chip Gaines",
        "Joanna Gaines","Tan France","Jonathan Van Ness","Mrs Hinch","Kim Woodburn","Jimmy Fallon",
        "Jimmy Kimmel","James Corden","Tom Gleeson","Julia Morris","Chrissie Swan"],
      WORLD: [
        "Kitchen","Bathroom","Garage","Attic","Basement","Backyard",
        "Hallway","Laundry","Pantry","Spare room","Front porch","Shed",
        "Balcony","Driveway","Letterbox","Garden path","Rooftop","Staircase",
        "Cupboard under the stairs","Linen closet","Nursery","Study","Sunroom","Deck",
        "Carport","Courtyard","Loft","Cellar","Utility room","Front gate",
        "Living room","Lounge","Dining room","Family room","Rumpus room","Games room",
        "Home office","Study nook","Home gym","Media room","Walk-in robe","Ensuite",
        "Powder room","Guest room","Kids room","Nursery corner","Playroom","Reading corner",
        "Window seat","Bay window","Alcove","Landing","Corridor","Entry hall",
        "Foyer","Mud room","Boot room","Coat cupboard","Broom cupboard","Linen press",
        "Airing cupboard","Butler's pantry","Walk-in pantry","Larder","Scullery","Wine rack",
        "Cellar steps","Trap door","Crawl space","Roof space","Manhole","Eaves",
        "Gable","Dormer","Skylight","Chimney stack","Roof ridge","Gutter",
        "Downpipe","Water butt","Rainwater tank stand","Verandah","Porch swing","Front steps",
        "Front gate latch","Garden path stones","Stepping stones","Gravel drive","Concrete drive","Garage door",
        "Workbench","Tool wall","Potting bench","Greenhouse","Glasshouse","Cold frame",
        "Vegetable bed","Raised bed","Herb spiral","Compost corner","Worm farm","Chook pen",
        "Rabbit hutch","Dog kennel","Cat door","Bird bath","Bird feeder","Wind chime",
        "Garden bench","Outdoor setting","Barbecue area","Fire pit","Pergola","Gazebo",
        "Shade sail","Awning","Deck rail","Balcony rail","Juliet balcony","Roof terrace",
        "Courtyard wall","Trellis fence","Picket fence","Front hedge","Letterbox post","Street number",
        "Driveway gate","Side gate","Back gate","Clothesline corner","Washing line pole","Septic lid",
        "Water meter","Gas meter","Electricity box","Fuse box","Switchboard","Hot water unit",
        "Air con unit","Solar inverter","Antenna mast","Satellite dish","Nature strip","Footpath",
        "Kerb","Street tree","Bin bay","Neighbour's fence","Party wall","Shared drive",
        "Cul de sac","Corner block","Battle axe block","Terrace row","Semi detached","Townhouse",
        "Apartment block","Unit","Flat","Bedsit","Studio","Loft conversion",
        "Granny flat","Bungalow","Cottage","Weatherboard","Federation home","Queenslander",
        "Beach shack","Farmhouse","Homestead","Barn conversion","Caravan","Mobile home",
        "Tiny house","Houseboat","Corner shop","Local hardware","Nursery garden centre","Op shop",
        "Tip shop","Recycling centre","Council depot","Hardware aisle","Paint counter","Timber yard",
        "Plumbing aisle","Light shop","Kitchen showroom","Bathroom showroom","Flooring shop","Curtain shop",
        "Furniture warehouse","Removalist truck","Storage unit","Real estate window","Open home","Auction sign"],
      RANDOM: [
        "Missing sock","Junk drawer","Squeaky door","Blown fuse","Leaky tap","Loose floorboard",
        "Spare key","Odd spoon","Dead batteries","Wrong-size screw","Tangled cables","Half-used paint tin",
        "Expired sauce","Random remote","Instruction manual","Broken zip","Old phone charger","Mystery stain",
        "Fridge leftovers","Dodgy shelf","Chore roster","Shopping list","Power bill","Spare button",
        "Rusty hinge","Sticky drawer","Draughty window","Wonky table leg","Warranty card","Blunt scissors",
        "Odd sock","Lost key","Dead remote","Flat battery","Blown bulb","Tripped switch",
        "Power cut","Water off","Cold shower","Blocked drain","Slow drain","Dripping tap",
        "Running toilet","Clogged filter","Full bin","Bin day","Missed bin day","Recycling mix-up",
        "Cardboard pile","Junk mail","Bills pile","Overdue notice","Rates notice","Insurance renewal",
        "Warranty expired","Manual in a drawer","Tangled charger","Wrong charger","Missing lid","Odd tupperware",
        "Leftover mystery","Freezer burn","Ice build-up","Expired milk","Stale bread","Wilted lettuce",
        "Empty jar","Last square of chocolate","Empty milk carton","Last loo roll","Wrong way loo roll","Empty shampoo",
        "Slippery soap","Hairball in the drain","Toothpaste squeeze","Cap left off","Seat left up","Towel on the floor",
        "Wet towel","Damp washing","Forgotten washing","Shrunken jumper","Colour run","Missing button",
        "Broken zipper","Ripped seam","Ironing pile","Sock drawer chaos","Wardrobe overflow","Under-bed box",
        "Attic clutter","Garage clutter","Shed spiders","Cobweb corner","Dusty shelf","Streaky window",
        "Smudged mirror","Scuffed skirting","Chipped paint","Peeling wallpaper","Squeaky hinge","Sticking door",
        "Draughty gap","Damp patch","Mould spot","Condensation","Fogged window","Creaky stair",
        "Loose tile","Cracked tile","Grout line","Silicone mould","Wobbly shelf","Uneven table",
        "Folded cardboard under a leg","Missing screw","Spare parts bag","Flat pack instructions","Allen key rage","Left over bolt",
        "Wrong size bracket","Wall anchor fail","Crooked picture","Nail hole","Filler patch","Touch up paint",
        "Test pot","Colour chart","Swatch on a wall","Furniture shuffle","Rug slip","Coffee ring",
        "Red wine stain","Crayon on the wall","Pet hair","Muddy paw print","Litter tray","Squeaky toy",
        "Chewed shoe","Scratched sofa","Cat on the keyboard","Dog at the door","Doorbell at dinner","Cold caller",
        "Parcel missed","Parcel in the bin","Neighbour's music","Barking at 6am","Lawnmower Sunday","Leaf blower Saturday",
        "Bin lid banging","Car alarm","Smoke alarm at 3am","Battery chirp","Wrong number","Nuisance text",
        "Group chat ping","Home wifi drop","Router restart","Password on a sticky note","Streaming argument","Remote hostage",
        "Volume war","Thermostat war","Window open or shut","Fan on or off","Blanket tug of war","Snoring",
        "Alarm snooze","Morning rush","School lunch scramble","Keys in the door","Shoes by the door","Shopping list on the fridge",
        "Fridge magnet poem","Family calendar","Chore chart","Pocket money","Sunday roast","Takeaway night",
        "Movie night","Board game night","Guest bed","Air mattress","Spare toothbrush","Guest towel",
        "Housewarming","Moving boxes","Bubble wrap","Removalist tape","Change of address","Meter reading",
        "Final bill","Bond return","Inspection day","Landlord visit"],
      DRAW: [
        "A kettle","A toaster","A vacuum cleaner","A mop and bucket","A washing machine","A front door",
        "A letterbox","A lawnmower","A ladder","A light bulb","A house plant","A garden hose",
        "A bin","A clothesline","A doormat","A tap dripping","A hammer","A screwdriver",
        "A paint roller","A wheelbarrow","A sofa","A bed","A dining table","A fridge",
        "A shower","A staircase","A window","A chimney","A garden gnome","A shed",
        "A dining chair","An armchair","A footstool","A coffee table","A bookshelf","A bookcase",
        "A cupboard","A drawer","A wardrobe","A mirror","A picture frame","A clock on a wall",
        "A calendar","A noticeboard","A key on a hook","A doorknob","A door handle","A keyhole",
        "A padlock","A bolt","A hinge","A doorbell","A welcome mat","A boot rack",
        "An umbrella in a stand","A coat on a hook","A hat on a peg","A scarf","A pair of slippers","A dressing gown",
        "A pillow","A duvet","A bunk bed","A cot","A high chair","A pram",
        "A toy box","A rocking chair","A lamp","A ceiling fan","A chandelier","A candle",
        "A fireplace","A log basket","A radiator","A heater","A fan","An air conditioner",
        "A thermostat dial","A power point","A plug","An extension cord","A light switch","A fuse box",
        "A smoke alarm","A torch","A battery","A remote control","A television","A speaker",
        "A radio","A telephone","A laptop on a desk","A printer","A desk chair","A filing tray",
        "A stapler","A hole punch","A pair of scissors","A roll of tape","A ball of string","A tool box",
        "A hammer and nail","A screwdriver and screw","A drill","A saw","A spanner","A wrench",
        "A pair of pliers","A tape measure","A spirit level","A paint tin and brush","A paint roller and tray","A ladder against a wall",
        "A step stool","A dust sheet","A bucket and sponge","A mop","A broom","A dustpan",
        "A vacuum","A feather duster","A washing basket","A peg on a line","An iron","An ironing board",
        "A washing machine door","A clothes dryer","A sewing machine","A needle and thread","A button","A pair of rubber gloves",
        "A bottle of spray","A scrubbing brush","A bin bag","A recycling box","A compost bin","A worm farm",
        "A watering can","A sprinkler","A rake","A spade in soil","A garden fork","A trowel",
        "A pair of secateurs","A hedge trimmer","A leaf blower","A pile of leaves","A garden glove","A plant pot",
        "A seed packet","A seedling","A trellis","A hanging basket","A window box","A bird bath",
        "A bird feeder","A wind chime","A garden bench","A picnic table","A barbecue","A fire pit",
        "A deck chair","A hammock","A swing seat","A trampoline","A paddling pool","A sandpit",
        "A cubby house","A tree swing","A dog kennel","A cat flap","A chicken coop","A rabbit hutch",
        "A fish tank","A bird cage","A pet bowl","A lead on a hook","A collar","A litter tray",
        "A scratching post","A pet bed","A garden gate","A picket fence","A hedge","A driveway",
        "A garage","A carport","A shed door","A greenhouse","A water tank","A solar panel",
        "A satellite dish","A chimney pot","A roof tile","A gutter","A downpipe","A skylight",
        "A front porch","A doorstep"],
  }, {
      OBJECT: [],
      NATURE: [],
      RANDOM: ["Squeaky floorboard","Jammed window","Lost TV remote","Empty ice tray"],
      ACTION: ["Rehanging a door","Bleeding a tap","Sanding a windowsill","Waxing a floor","Sealing a draught"],
      PERSON: ["Alan Titchmarsh","Monty Don","Charlie Dimmock","Nick Knowles","George Clarke","Kirstie Young",
        "Amanda Keller","Larry Emdur","David Koch","Natalie Barr","Sonia Kruger","Grant Denyer","Osher Gunsberg",
        "Dr Chris Brown","Lisa McCune"],
      WORLD: ["Sunroom nook","Laundry chute"],
      DRAW: [],
  
  }),

  deck("Music Icons", "teens", "note",
    "Artists, instruments and the songs that get sung badly at every party.", {
      OBJECT: [
        "Electric guitar","Drum kit","Microphone","Vinyl record","Headphones","Keyboard",
        "Amplifier","Saxophone","Tambourine","Turntable","Guitar pick","Drum stick",
        "Violin","Harmonica","Trumpet","Ukulele","Speaker stack","Mixing desk",
        "Setlist","Tour bus","Backstage pass","Stage light","Smoke machine","Capo",
        "Banjo","Cello","Bass guitar","Piano stool","Music stand","Metronome"],
      NATURE: [
        "Nightingale","Songbird","Dawn chorus","Whale song","Wolf","Cricket",
        "Birdsong","Thunder","Ocean waves","Babbling brook","Waterfall","Canyon",
        "Cave","Howling wind","Rain","Beehive","Frog","Cicada",
        "Kookaburra","Magpie","Humpback whale","Lyrebird","Mockingbird","Canary",
        "Cockatoo","Woodpecker","Owl","Seagull","Echo","Storm"],
      ACTION: [
        "Headbanging","Crowd surfing","Air guitar","Singing along","Busking","Jamming",
        "Beatboxing","DJing","Moshing","Taking a bow","Sound check","Lip syncing",
        "Freestyling","Harmonising","Whistling a tune","Tapping a beat","Clapping along","Waving a lighter",
        "Stage diving","Dropping the bass","Recording a demo","Going on tour","Signing autographs","Warming up vocals",
        "Tuning a guitar","Writing lyrics","Sampling","Remixing","Conducting","Drum solo"],
      PERSON: [
        "Elvis Presley","The Beatles","Beyoncé","Freddie Mercury","Taylor Swift","Bob Marley",
        "Dolly Parton","Michael Jackson","Adele","Ed Sheeran","Nirvana","Queen",
        "AC/DC","INXS","Prince","Whitney Houston","David Bowie","Rihanna",
        "Bruno Mars","Billie Eilish","Bruce Springsteen","Aretha Franklin","Amy Winehouse","Johnny Cash",
        "Bob Dylan","Jimi Hendrix","Tina Turner","Elton John","Stevie Wonder","Usher"],
      WORLD: [
        "Abbey Road","Nashville","Glastonbury","Coachella","Sydney Opera House","Woodstock",
        "Motown","Broadway","Ibiza","Detroit","Liverpool","New Orleans",
        "Memphis","Hollywood Bowl","Vienna","Splendour in the Grass","Tamworth","Royal Albert Hall",
        "Carnegie Hall","Red Rocks","Recording studio","Concert hall","Music festival","Karaoke bar",
        "Record shop","Rehearsal room","Radio station","Nightclub","Busker corner","Grand Ole Opry"],
      RANDOM: [
        "Earworm","One-hit wonder","Album cover","Encore","Chart topper","Guilty pleasure",
        "Karaoke","Playlist","Mixtape","Fan club","Boy band","Girl group",
        "Cover version","Duet","Riff","Chorus","Bridge","Falsetto",
        "Power ballad","Air drums","Vinyl revival","Streaming numbers","Gold record","Groupie",
        "Band merch","Festival wristband","Dad rock","Autotune","Lyric video","Support act"],
      DRAW: [
        "An electric guitar","A drum kit","A microphone","A vinyl record","A pair of headphones","A piano",
        "A saxophone","A trumpet","A speaker","A DJ deck","A music note","A tambourine",
        "A guitar pick","A violin","A harmonica","A ukulele","A boombox","A stage",
        "A tour bus","A concert crowd","A cassette","A conductor's baton","A treble clef","A jukebox",
        "A megaphone","A festival tent","A wristband","A vinyl sleeve","A metronome","A karaoke machine"],
  }),

  deck("Food & Drink", "family friendly", "cup",
    "Meals, snacks and drinks. Easy to picture, surprisingly tricky to describe without saying the word.", {
      OBJECT: [
        "Frying pan","Wooden spoon","Rolling pin","Cheese grater","Teapot","Cutting board",
        "Whisk","Baking tray","Measuring cup","Can opener","Cocktail shaker","Salad bowl",
        "Pepper grinder","Ice tray","Lunch box","Thermos","Straw","Corkscrew",
        "Toaster","Blender","Barbecue plate","Pizza cutter","Egg cup","Mixing bowl",
        "Ladle","Slow cooker","Coffee plunger","Sushi mat","Skewer","Apron"],
      NATURE: [
        "Tomato vine","Apple tree","Beehive","Wheat field","Coffee bean","Cocoa pod",
        "Olive grove","Hop field","Herb garden","Wild truffle","Lemon tree","Chilli plant",
        "Corn field","Rice paddy","Maple tree","Salt flats","Fresh water spring","Cinnamon bark",
        "Berry bush","Pumpkin vine","Avocado tree","Banana palm","Mango tree","Potato field",
        "Strawberry patch","Grapevine","Peanut plant","Sunflower seed","Fig tree","Wild mint"],
      ACTION: [
        "Barbecuing","Baking","Boiling","Whisking","Kneading","Marinating",
        "Toasting","Grilling","Simmering","Chopping","Peeling","Stirring",
        "Flipping a pancake","Icing a cake","Slicing bread","Frying an egg","Making a sandwich","Setting the table",
        "Pouring a drink","Blowing on soup","Doing the dishes","Ordering takeaway","Booking a table","Sharing dessert",
        "Snacking","Meal prepping","Taste testing","Seasoning","Plating up","Washing veggies"],
      PERSON: [
        "Gordon Ramsay","Jamie Oliver","Nigella Lawson","Julia Child","Matt Moran","Neil Perry",
        "Colin Fassnidge","Marion Grasby","Curtis Stone","Maggie Beer","Matt Preston","Anthony Bourdain",
        "Heston Blumenthal","Mary Berry","Paul Hollywood","Wolfgang Puck","Ina Garten","Guy Fieri",
        "Marco Pierre White","Rick Stein","Adriano Zumbo","Poh Ling Yeow","Manu Feildel","Ainsley Harriott",
        "Julie Goodwin","Donna Hay","Kylie Kwong","Adam Liaw","Gary Mehigan","Melissa Leong"],
      WORLD: [
        "Bakery","Farmers market","Food truck","Fish and chip shop","Cafe","Vineyard",
        "Pizzeria","Ice cream parlour","Night market","Buffet","Supermarket","Butcher shop",
        "Bistro","Beer garden","Rooftop bar","Diner","Sushi train","Deli",
        "Orchard","Brewery","Country pub","Street food stall","Bakery window","Fruit stand",
        "Cellar door","Test kitchen","Canteen","Picnic spot","Barbecue area","Food hall"],
      RANDOM: [
        "Leftovers","Secret recipe","Food coma","Midnight snack","Doggy bag","Brunch",
        "Side dish","Comfort food","Guilty pleasure","Spice level","Recipe fail","Burnt toast",
        "Soggy chips","Melted ice cream","Fizzy drink","Second helping","Sharing platter","Dessert menu",
        "Happy hour","Takeaway night","Packed lunch","Picnic blanket","Hot sauce","Pickle jar",
        "Cheese board","Roast dinner","Sunday lunch","Street food","Meal deal","Bottomless cup"],
      DRAW: [
        "A pizza slice","An ice cream cone","A burger","A cup of coffee","A birthday cake","A banana",
        "A pineapple","A hot dog","A fried egg","A cupcake","A teapot","A wine glass",
        "A watermelon slice","A bunch of grapes","A loaf of bread","A doughnut","A bowl of noodles","A taco",
        "A milkshake","A chef's hat","A frying pan","A barbecue","A picnic basket","A lollipop",
        "A pretzel","A sushi roll","A carrot","A chilli","A jar of honey","A toaster with toast"],
  }),

  deck("Adults After Dark 🔞", "adults (spicy)", "moon",
    "Rude, cheeky and firmly after bedtime. Keep this one away from the kids' table.", {
      OBJECT: [
        "Handcuffs","Lace lingerie","Whipped cream","Red wine","Tequila shot","Feather boa",
        "Silk sheets","Massage oil","Pole dancing pole","Blindfold","Fishnet stockings","Corset",
        "High heels","Bar tab","Fake ID","Beer bong","Playing cards","Dice cup",
        "Karaoke mic","Neon sign","Bottle of bubbly","Cigar","Poker chips","Lipstick",
        "Little black dress","Bow tie","Champagne flute","Hip flask","Chocolate body paint","Mirror ball"],
      NATURE: [
        "Melons","Moonlit beach","Hot spring","Secluded waterfall","Beaver","Full moon",
        "Peach","Banana","Love birds","Rabbit","Stallion","Lioness",
        "Snake","Peacock","Bull","Coconuts","Cherry","Cucumber",
        "Night owl","Mating season","Morning dew","Tropical storm","Steamy jungle","Volcano heat",
        "Deserted cove","Pussy willow","Starry night","Birds and the bees","Eggplant","Heatwave"],
      ACTION: [
        "Flirting","Skinny dipping","Pub crawl","Strip poker","Speed dating","Sliding into DMs",
        "Ghosting","Swiping right","Hangover","Walk of shame","Truth or dare","Spin the bottle",
        "Body shot","Shotgunning a beer","Karaoke duet","Last orders","Cheeky snog","Chatting someone up",
        "Blind date","Beer pong","Dad dancing","Kicking on","Big night out","Sneaking out",
        "Making eyes","Late-night kebab","Hair of the dog","Boozy brunch","Bar hopping","Nightcap"],
      PERSON: [
        "Marilyn Monroe","Hugh Hefner","Bettie Page","Brigitte Bardot","Sophia Loren","Raquel Welch",
        "Farrah Fawcett","Elizabeth Taylor","Mae West","Casanova","Cleopatra","Errol Flynn",
        "Madonna","Cher","Dita Von Teese","Lady Gaga","Mick Jagger","Barry White",
        "Tom Jones","Prince","Rod Stewart","Warren Beatty","George Clooney","Fabio",
        "Pamela Anderson","Paris Hilton","Kim Kardashian","Jennifer Lopez","Shakira","Russell Brand"],
      WORLD: [
        "Las Vegas","Amsterdam","Ibiza","Nightclub","Strip club","Casino",
        "Honeymoon suite","Kings Cross","Rio carnival","Bourbon Street","Bali","Magaluf",
        "Monte Carlo","Speakeasy","Hotel bar","Hotel jacuzzi","Cruise ship","Bachelor pad",
        "Love hotel","Red light district","Bangkok","New Orleans","Berlin club","Vegas chapel",
        "Beach club","Penthouse","Dive bar","Cabaret","Burlesque show","Pool party"],
      RANDOM: [
        "Hickey","Dad bod","Beer goggles","Netflix and chill","Booty call","Wingman rules",
        "Bad tattoo","Regrettable text","Dirty martini","Hangxiety","Ex's new partner","Love bite",
        "Bar tab shock","Morning after","Drunk dial","Slurred speech","Kebab shop queue","Sneaky pash",
        "Cheeky Nando's","Last drinks","Awkward silence","Flirty emoji","Red flag","Green flag",
        "Situationship","Rebound","Dating app bio","Group chat gossip","Wedding speech","Bad chat-up line"],
      DRAW: [
        "A cocktail","A pair of handcuffs","A pair of high heels","A love heart","A wine glass","A disco ball",
        "A pair of lips","A neon sign","A bottle of champagne","A pair of dice","A poker hand","A martini",
        "A bow tie","A lipstick","A rose","A candle","A hot tub","A bed",
        "A cocktail umbrella","A shot glass","A leather jacket","A tattoo","A key to a hotel room","A do not disturb sign",
        "A moon","A cigar","A limousine","A microphone stand","A love letter","A pair of sunglasses at night"],
  }),

  deck("Classic Mixed Bag", "adults (clean)", "dice",
    "A bit of everything, so no single person at the table has the advantage.", {
      OBJECT: [
        "Umbrella","Wallet","Suitcase","Compass","Telescope","Hourglass",
        "Padlock","Wheelbarrow","Anchor","Ladder","Typewriter","Globe",
        "Binoculars","Magnifying glass","Chessboard","Piano","Bicycle","Lantern",
        "Mirror","Basket","Rope","Bucket","Shovel","Broom",
        "Candle","Camera","Newspaper","Backpack","Clock","Kite"],
      NATURE: [
        "Volcano","Waterfall","Glacier","Desert","Rainforest","Coral reef",
        "Thunderstorm","Avalanche","Cave","Canyon","Tornado","Earthquake",
        "Iceberg","Sand dune","Geyser","Swamp","Meadow","Fjord",
        "Tundra","Savannah","Lightning","Eclipse","Comet","Rainbow",
        "Tide","Monsoon","Whirlpool","Sinkhole","Delta","Reef"],
      ACTION: [
        "Juggling","Whistling","Tiptoeing","Yawning","Sneezing","Snoring",
        "Shivering","Wrestling","Skydiving","Hitchhiking","Camping","Fishing",
        "Knitting","Gardening","Painting","Sculpting","Meditating","Stretching",
        "Sprinting","Swimming","Climbing","Digging","Rowing","Sailing",
        "Cycling","Bargaining","Queuing","Celebrating","Apologising","Daydreaming"],
      PERSON: [
        "Albert Einstein","Cleopatra","Leonardo da Vinci","Marie Curie","Nelson Mandela","William Shakespeare",
        "Amelia Earhart","Neil Armstrong","Mozart","Frida Kahlo","Isaac Newton","Julius Caesar",
        "Joan of Arc","Charles Darwin","Vincent van Gogh","Mahatma Gandhi","Queen Elizabeth","Napoleon",
        "Rosa Parks","Alexander Fleming","Abraham Lincoln","Martin Luther King Jr","Winston Churchill","Beethoven",
        "Michelangelo","Anne Frank","Florence Nightingale","Nikola Tesla","Galileo","Jane Austen"],
      WORLD: [
        "Eiffel Tower","Great Wall of China","Pyramids","Colosseum","Taj Mahal","Machu Picchu",
        "Stonehenge","Grand Canyon","Niagara Falls","Mount Everest","Venice","Tokyo",
        "Cairo","Rome","Paris","Amazon rainforest","Sahara","Antarctica",
        "Iceland","Serengeti","New York","London","Istanbul","Athens",
        "Petra","Angkor Wat","Easter Island","Galápagos","Santorini","Kyoto"],
      RANDOM: [
        "Déjà vu","Superstition","Traffic jam","Queue jumper","Lost luggage","Rainy day",
        "Spring clean","Time zone","Leap year","Full moon","Rush hour","Paper cut",
        "Brain freeze","Butterflies","Goosebumps","Alarm clock","Snooze button","To-do list",
        "Small talk","Wrong number","Double booking","Autocorrect fail","Flat tyre","Missing sock",
        "Dead phone","Spilt coffee","Long weekend","Public holiday","Group photo","Awkward hug"],
      DRAW: [
        "A lighthouse","A hot air balloon","A windmill","A treasure map","A telescope","A pyramid",
        "A castle","A bridge","A train","A submarine","A rocket","A parachute",
        "An anchor","A compass","An hourglass","A key","A crown","A ladder",
        "A chessboard","A globe","An umbrella","A campfire","A tent","A canoe",
        "A volcano","A rainbow","A snowflake","A cactus","A palm tree","A shopping trolley"],
  }),

  ];
})();
